### ISSUE TITLE
Pop Up

### ISSUE THREAD

**Issue by KasiaWM** [trinitywebmedia/Norwescap-Tickets#10]
Hey So the pop up disappeared 
Can we put back a pop up and use this image instead?
Thanks. 

![ONE DAY TWO EVENTS (3)](https://user-images.githubusercontent.com/83297632/118717463-19f01600-b7f4-11eb-8fbb-222c6e6d3336.png)

**Comment by trinitywebmedia** [comment]
The popup still works as I just checked. You are probably viewing the site from a cached version with a cookie that has not expired. I just took this screenshot with my alt-browser. -- GT

<img width="1439" alt="Screen Shot 2021-05-18 at 4 20 57 PM" src="https://user-images.githubusercontent.com/31321275/118718368-24f77600-b7f5-11eb-84c8-9fadd03bb7ed.png">

MOBILE:

![IMG_5107FDA7640A-1](https://user-images.githubusercontent.com/31321275/118718898-caaae500-b7f5-11eb-844a-80bd07eb933b.jpeg)

**Comment by trinitywebmedia** [comment]
We can create a new popup with dev hours and use the existing artwork. 

Question: Does it make sense to have a link of norwescap.org on the popup when the only way people are seeing that popup is if they are already at that url. Maybe the art can be changed to tickets.norwescap.org?

Also, where should this popup link? The event landing page with Event info or the ticket site where there is minimal event information? 

Please advise and I will schedule the dev -- GT

**Comment by KasiaWM** [comment]
Greg good point. 
As long as the pop up is back and running, lets leave it for now. 
Can you make the Form update/event button and covid archive priority for dev hours? 
Covid thing is driving Mark up to the moon.
-K

**Comment by trinitywebmedia** [comment]
For now, we will close this issue. Please let us know if you want us to change the popup or CTA in the future. [Other comments re: dev priority are noted, and will be discussed with Kevin at our morning meeting.] -- GT
