### ISSUE TITLE
Updates to Events page

### ISSUE THREAD

**Issue by hlthomps** [trinitywebmedia/Norwescap-Tickets#102]
Hi,

Please update https://norwescap.org/upcoming-events/ with the text in the attached Word document. Thank you!

Heather
[2022 March Events page update.docx](https://github.com/trinitywebmedia/Norwescap-Tickets/files/8188200/2022.March.Events.page.update.docx)

**Comment by trinitywebmedia** [comment]
Hi Heather -- We've exceed our monthly site hours as per August's agreement. I made over 15 changes to the site for CFRS. Please expect an email from Kevin, so you two can set up a time to figure out how to proceed. I will wait to here the resolution and then take care of the events updates. -- Thanks GT

**Comment by trinitywebmedia** [comment]
Just spoke to Kevin since you guys are talking on Monday the changes were made and we figure the rest out post-call. Have a nice weekend. -- GT
