### ISSUE TITLE
Link update on "Get Involved" Page

### ISSUE THREAD

**Issue by hlthomps** [trinitywebmedia/Norwescap-Tickets#105]
On the Get Involved page: https://norwescap.org/get-involved/, Under the Advocacy section:

Please update the link for both the word "subscribe" in "subscribe to Norwescap’s Newsletter", as well as the "Norwescap Newsletter" icon below, to link to: http://eepurl.com/hrlQXD

**Comment by trinitywebmedia** [comment]
DONE -- GT
