### ISSUE TITLE
Apply For Assistance/WIC

### ISSUE THREAD

**Issue by keberletwm** [trinitywebmedia/Norwescap-Tickets#107]
Received from Heather Thompson 3/16/22
Can you please tell me whether the "Apply for Assistance" button on the WIC page: https://norwescap.org/health-wellness/wic/, is unique to that page? Or is it embedded in the left menu? Our team would like to link the button specifically on the WIC page to a different form, but we do not want it to affect that button on any of the other pages.

This is the link for the WIC-specific form: https://portal.empoworbycsst.com/Public/ClientAccessForm.aspx?AccessID=70314490-533b-4841-a786-6a9a0e217c05 (it looks the same as the other one, but it's a different ID
 
If that button is embedded in the menu and can't be changed without affecting other pages, we would like to add a link (large font) to the above form saying "Apply for WIC" directly under the text "Pregnant women, new mothers, infants and children up to the fifth birthday with income below 185% of poverty"

**Comment by trinitywebmedia** [comment]
I will look at this today -- GT

**Comment by trinitywebmedia** [comment]
Heather -- the button on the left side bar is used for all the pages that fall under the Health & Wellness Programs (Labeled onsite as the former name 'Health & Nutirtion') :: We have two options here 1) Change all the buttons on the 'Programs' listed on the sidebar on https://norwescap.org/health-wellness/ to the desired link or create a whole new WIC sidebar that is specific to just  https://norwescap.org/health-wellness/wic/ along with another button under the above designated paragraph.

Please let me know how you wish to proceed.

**Comment by hlthomps** [comment]
Thanks. We definitely do not want to use the form for all health programs, so we need to find a solution unique to the WIC page. Can you give me an estimate of how many hours would be used up creating that new sidebar just for that page? I don't want to use up a lot of dev time on this so if that is going to be too time consuming, I'd prefer to find a simpler solution (or ask the team how important this really is). Thanks.

**Comment by trinitywebmedia** [comment]
I think it will take about an hour to create a new sidebar, place and test with the button needed. -- GT

**Comment by hlthomps** [comment]
Ok - let's move ahead with the new sidebar for the WIC page. Please let me know if there is any other information you need from me. Thanks.

**Comment by trinitywebmedia** [comment]
Ok, sounds good. I will try and knock this out early tomorrow. -- GT

**Comment by trinitywebmedia** [comment]
Heather -- I think I have this completed. Please review https://norwescap.org/health-wellness/wic/ and let me know if this is inline with what you wanted. 

I created a custom sidebar for the /wic page -- this means you can populate the sidebar with anything specifically related to the initiative. -- GT

**Comment by hlthomps** [comment]
Greg, I think we're good to go! I will have the program team double check and let you know if there are any issues, but it seems correct to me. Thanks.

**Comment by trinitywebmedia** [comment]
Sounds good, I am going to close this issue. If anything changes, please re-open. Thanks -- GT
