### ISSUE TITLE
Add File

### ISSUE THREAD

**Issue by cfrsnorwescap** [trinitywebmedia/Norwescap-Tickets#110]
https://norwescap.org/education/child-and-family-resource-services/

On the above website, please upload the attached file to the "Current Childcare Services Policies" section at the top of the page & label the attached file as "April 2022 Provider Notice Attendance Study"

[DFDI 22-03-05--Attachment 1 Provider Notice Attendance Study.pdf](https://github.com/trinitywebmedia/Norwescap-Tickets/files/8399390/DFDI.22-03-05--Attachment.1.Provider.Notice.Attendance.Study.pdf)

**Comment by trinitywebmedia** [comment]
Thank you for sending. I am adding Heather as a collaborator to approve dev time. -- GT

**Comment by hlthomps** [comment]
Thanks, Greg. Since we are in April now, we have our April hours to draw from as well as the remaining hours from the additional ones we purchased, correct? Do you anticipate this taking more than 1 hour?

**Comment by trinitywebmedia** [comment]
Thank you Heather. This request should take between 30 min - 1 hour total depending on the size of the pdf. I will schedule to finish on Monday. -- GT

**Comment by hlthomps** [comment]
Great. Thanks!

**Comment by trinitywebmedia** [comment]
Done. 30 mins -- GT
