### ISSUE TITLE
Events page updates

### ISSUE THREAD

**Issue by hlthomps** [trinitywebmedia/Norwescap-Tickets#112]
Please update the content on https://norwescap.org/upcoming-events/ to reflect the following changes:

_Earth Day - Plant a Tree event - update text to:_

**Earth Day – Plant a Tree
Friday, April 22, 2022, 10am – 1pm
TJ Dunn Community Park, Sussex Borough**

Through the generosity of JCP&L’s “Invest in our Planet” initiative, 500 saplings will be donated to help beautify parks and green spaces around Sussex in honor of Earth Day! We are seeking volunteers to give back to our planet by planting saplings throughout Sussex Borough. Families with kids of all ages are welcome; volunteers will meet at TJ Dunn Community Park and go out in teams to various locations. **To sign up as a volunteer, [click here](https://www.volgistics.com/appform/1849720485).**

_Add the following text after the Earth Day event:_

**Phillipsburg Community Day of Action: Community Clean-Up
Saturday, April 23, 2022, 8:30 – 11am
Shappell Park, Phillipsburg**

Calling all Phillipsburg residents and neighbors! Volunteer for Norwescap’s 4th Annual Community Day of Action and show your love for your community. Volunteers will be cleaning up and sprucing up Phillipsburg's South Main Street District, starting at Shappell Park and spreading out to clean up all the streets from Union Square to Stockton, Sitgreaves to Howard. All you need is a broom; if you don't have one, we'll supply that along with gloves, dust pans, garbage bags, masks and litter grabbers. Check-in starts 8:30am at Shappell Park and clean-up begins at 9:00am. You, or your team will be assigned to a location and then we will all meet back at Shappell Park at 11am. **[Click here](https://www.eventbrite.com/e/norwescap-4th-annual-community-day-of-action-tickets-293934836007) for more details and to register as a volunteer!** 
_Same-day sign-in is an option but will not guarantee your team will be assigned to the same area._

**Comment by trinitywebmedia** [comment]
DONE -- GT
