### ISSUE TITLE
Updates to Reports and Publications Page

### ISSUE THREAD

**Issue by hlthomps** [trinitywebmedia/Norwescap-Tickets#113]
Please update the page https://norwescap.org/reports-publications/ with the following:

Under Norwescap Annual Reports
Add "Norwescap 2021 Annual Report" with link to the attached pdf
Remove "Norwescap 2017 Annual Report"

Under Norwescap Audited Financial Statements
Add "Norwescap Audited Financials FY21" with link to the attached pdf
Remove "Norwescap Audited Financials FY18"

Thank you!
[2021 Annual Report FINAL (reduced size).pdf](https://github.com/trinitywebmedia/Norwescap-Tickets/files/8452348/2021.Annual.Report.FINAL.reduced.size.pdf)

[Norwescap Audited Financials FY21 (8.31.21).pdf](https://github.com/trinitywebmedia/Norwescap-Tickets/files/8452349/Norwescap.Audited.Financials.FY21.8.31.21.pdf)

**Comment by trinitywebmedia** [comment]
DONE -- GT
