### ISSUE TITLE
Additional updates to Events page

### ISSUE THREAD

**Issue by hlthomps** [trinitywebmedia/Norwescap-Tickets#114]
A couple of other minor updates to https://norwescap.org/upcoming-events/:

Please change the link for "subscribe to our e-newsletter" in the first paragraph to link to this signup form: https://norwescap.us11.list-manage.com/subscribe?u=73d9c80498d5cb56648adf2e8&id=9438896dc6

Please add a sentence at the end of the NorwesFest listing:
**Sign up for our e-newsletter and be the first to know when tickets go on sale!**
With the "Sign up for our e-newsletter" linking to the same link as above

Thanks!

**Comment by trinitywebmedia** [comment]
DONE -- GT
