### ISSUE TITLE
Addition of Document

### ISSUE THREAD

**Issue by cfrsnorwescap** [trinitywebmedia/Norwescap-Tickets#115]
https://norwescap.org/education/child-and-family-resource-services/

On the above website, please upload the attached document under the heading "Current Childcare Services Policies" at the top of the page. Please label the document: Hiring and Retention Bonus Re-Opening Letter to Providers(April 2022)
[Hiring_Retention_Bonus_Reopening_Letter.pdf](https://github.com/trinitywebmedia/Norwescap-Tickets/files/8455182/Hiring_Retention_Bonus_Reopening_Letter.pdf)

**Comment by trinitywebmedia** [comment]
DONE -- GT
