### ISSUE TITLE
Upload Document

### ISSUE THREAD

**Issue by cfrsnorwescap** [trinitywebmedia/Norwescap-Tickets#116]
https://norwescap.org/education/child-and-family-resource-services/

On the above website, please upload the attached document under the heading "Current Childcare Services Policies" at the top of the page. Please label the document: NJ ARP Stabilization Grant Announcement Reminder
[NJ_ARP_Stabilization_Grant_Reminder_Announcement.pdf](https://github.com/trinitywebmedia/Norwescap-Tickets/files/8455185/NJ_ARP_Stabilization_Grant_Reminder_Announcement.pdf)

**Comment by trinitywebmedia** [comment]
DONE -- GT
