### ISSUE TITLE
Updated Applications to upload

### ISSUE THREAD

**Issue by cfrsnorwescap** [trinitywebmedia/Norwescap-Tickets#118]
https://norwescap.org/education/child-and-family-resource-services/

On the above website, under the Applications for Child Care Subsidy heading, there are two linked applications - one in English and one in Spanish. We need those applications replaced with the attached applications as income guidelines have changed. 

English:
[Subsidy Application Packet Color 3-22-2022 (1).pdf](https://github.com/trinitywebmedia/Norwescap-Tickets/files/8523561/Subsidy.Application.Packet.Color.3-22-2022.1.pdf)

Spanish:
[NJCK  Application Spanish  03-22-2022.pdf](https://github.com/trinitywebmedia/Norwescap-Tickets/files/8523567/NJCK.Application.Spanish.03-22-2022.pdf)

**Comment by trinitywebmedia** [comment]
DONE -- GT
