### ISSUE TITLE
NorwesFest ticket form

### ISSUE THREAD

**Issue by hlthomps** [trinitywebmedia/Norwescap-Tickets#120]
Hello,

We're getting ready to update the NorwesFest event page for 2022 and I want to start working on the ticketing form. This year's should be much simpler than last year's because we are not requiring guests to pre-select meals. With that said, would there be an option to include both the daytime event tickets and evening tickets on the same form, and just allow guests to choose quantity for each type of ticket they want? 

I've attached the basics of what I have in mind for the form, but not knowing the nuances of WP Give, I'm not sure if this will all work. I would also want to make sure the confirmation the donor receives shows the quantity of each ticket type purchased along with guest names, and that we receive that same information so we can capture not just the monetary gift, but the details. Please let me know if you'd like to schedule a call to talk through this. 

Thanks,
Heather
[NorwesFest 2022 ticketing form outline.docx](https://github.com/trinitywebmedia/Norwescap-Tickets/files/8526388/NorwesFest.2022.ticketing.form.outline.docx)

**Comment by trinitywebmedia** [comment]
Thank you for getting this to us early. We actually do not use Give for the tickets. Since last year there were so many variables and conditional logic (if this then that happens) on the form I custom built the system using Gravity Forms. 

Let me review your doc today and I will respond here with some thoughts. -- GT

**Comment by trinitywebmedia** [comment]
Heather -- The form as you have it is doable. I can program some logic around the quantity of tickets determining how many Guest Name Fields appear. Also, the write in your own donation is no problem. 

Please let me know if this is or is close to the final version of the form and I can schedule some dev time for the system. We can use banked hours from the 10 hour block so there should not be any additional costs to Norwescap.

**Comment by hlthomps** [comment]
Great! I've made a few updates to the form text - mostly just adding a bit of text to explain what's included with each ticket type. See the Word doc attached (the highlighted parts are just the instructional parts). One form change is that for child guests, rather than ask for name and email, I'd like to ask for name and age if possible. again, if it becomes difficult to have separate fields for each guest, we can do this via open text boxes. 

I'd also like to include the NorwesFest logo at the top of the form if possible (attached).

Thank you!
[NorwesFest 2022 ticketing form outline.docx](https://github.com/trinitywebmedia/Norwescap-Tickets/files/8543142/NorwesFest.2022.ticketing.form.outline.docx)
[NorwesFest Logo - General](https://user-images.githubusercontent.com/83599303/164771992-eefe9688-4092-4412-9966-f700329b385d.png)

**Comment by hlthomps** [comment]
Hello - I'm attaching the text for the confirmation email that should be sent when this form is completed. I assume it can be built to pull in all the details about how many tickets of each type the donor purchases, guest names and emails, any extra donation they included, etc. Please let me know if there are any questions or concerns. 

I also want to make sure that both Michele Kennedy (kennedym@norwescap.org) and I are copied on all confirmation emails sent out, so we can ensure we're tracking all guests' details properly.

Please let me know if there are any questions or concerns. Thank you!
[Ticket Purchase Confirmation Email.docx](https://github.com/trinitywebmedia/Norwescap-Tickets/files/8566972/Ticket.Purchase.Confirmation.Email.docx)

**Comment by trinitywebmedia** [comment]
Perfect, Thank you Heather. I will have this completed on tickets.norwescap.org by tomorrow and sent to you for testing. -- GT

**Comment by trinitywebmedia** [comment]
Heather --- Can you please test this form for me, and let me know your thoughts. https://tickets.norwescap.org/
Once this is approved, I will finalize the confirmation Email process. Thanks -- GT

**Comment by hlthomps** [comment]
Hi Greg,

Thanks for sending. I’m running into some hiccups:

  *   The form is only allowing me to choose one event or the other. I’d prefer to have an option for people to choose both if possible, as last year we had some guests who brought their kids during the day and then came back in the evening.
  *   When I select the number of tickets for Family Fun Day, it requests the primary guest’s name and email – which is fine – but if the only way to capture info for “additional guests” is the open text box, then we need to add more specific instructions. It’s especially important for us that we capture adult guests vs kid guests so we have appropriate quantities of food, drinks, etc. So I’d want that field title to say something like “Additional Guests: Please list each guest’s name and specify “Adult” or “Child” for each.”
  *   After I filled in the guest names, I hit “submit” but I got an error message (see screenshot below). There were no fields that came up for payment, but the error seems to be related to not having entered credit card info.
  *   When I selected “Sunset Social Affair” and entered 2 tickets, the payment fields did appear below, but the Total was still showing “0.” I filled in $2.00 to the “I would like to make an additional donation” box and then the Total field calculated to “$2.00.” So it doesn’t seem to be totaling from the ticket selection or quantities at all.
  *   Beyond the required field for guest name and email, there is nowhere on the form for address, phone number, etc. We need that to ensure we can properly communicate with and thank the donor and that we credit the purchase to the right person in our system.
  *   I did try to run the $2.00 on my real credit card, but I got a “Your payment has failed.” Message. Not sure if that’s just because the form isn’t officially hooked up yet or if there is some other issue.
Let me know if you need clarification on anything. Thanks.
Heather


***@***.***

**Comment by trinitywebmedia** [comment]
Let me check some settings on this live site and shoot you a note with what I find. 

Also I will add the contact info fields for communications. 

Thanks - GT

**Comment by trinitywebmedia** [comment]
Heather -- I just re-vamped the ticketing system. Please check it out and let me know your thoughts. I ran my cc for a write in donation and it processed. Again, once tested -- I will move on to the confirmation email and reporting. Thanks - GT

**Comment by hlthomps** [comment]
Thanks, Greg. That is working much better. On screen 2, for the Family Fun Day Tickets – I want to make it easy for guests who are ONLY buying Sunset Social tickets to bypass this – maybe text at the top in a stand-out font color saying If you are only attending the evening event, enter “0” for quantity and click “Next”  ?

I didn’t actually run my credit card through, but I will do that once the thank you message is set up and in place so I can test that as well – since I need to buy tickets for my husband and son anyway!

**Comment by trinitywebmedia** [comment]
I added that text, and tomorrow morning I will complete the Thank You message. Once live, I will also test since Alli, and I plan on attending. Thank you.

**Comment by hlthomps** [comment]
Sounds great. Thank you!

**Comment by trinitywebmedia** [comment]
Heather -- Receipts and confirmations are ready for testing. When it's a go and when you are ready, I will add a button to the NorwesFest page to drive people to the ticketing site. Please let me know if there are any other changes you would like to see. Thanks! -- GT

**Comment by hlthomps** [comment]
Hi Greg  -thanks. I just went through and purchased 2 daytime tickets and the process went smoothly for the most part. A couple of things:
On the first screen can we change "Guest Name" to "Name of Ticket Purchaser"? There might be cases where someone is buying tickets for other people but is not attending themselves so I want to be clear on this (as I did for my husband and son this morning).
On the confirmation screen, can we remove the line "If you are unable to attend, but wish to make a donation, you can do so here" since they have already purchased tickets at this point?
I received the ticket purchase email that will come to Michelle and me - which is great and has all the detail we need - but the confirmation I received as a ticket buyer only said this at the bottom (under the language I had drafted):

Purchase Details

2

Ryan Wangner - adult
Nolan Wangner - 6

$20.00 


If at all possible I would prefer that section include more detail, i.e.:

Purchase Details

Ticket Quantity for Family Fun Fest: 2

Guest Names:
Ryan Wangner
Nolan Wangner - 6

Ticket Quantity for Sunset Social Affair:

Guest Names:

Additional Donation: 

Total Purchase/Contribution: $20

Or - could it even pull in the exact same information laid out the way Michele and I are seeing it in the confirmation we receive? I've attached that here for reference (I copied it into a Word doc since the .msg format isn't supported).
Thanks!

[NorwesFest Ticket Confirmation Email (to Norwescap).docx](https://github.com/trinitywebmedia/Norwescap-Tickets/files/8590927/NorwesFest.Ticket.Confirmation.Email.to.Norwescap.docx)

**Comment by trinitywebmedia** [comment]
I'll have this dialed in by noon today. Thank you for your testing and feedback. -- GT

**Comment by trinitywebmedia** [comment]
Heather -- I made the requested changes. I've attached a screenshot of my ticket purchase detail email
![Purchase Confirmation](https://user-images.githubusercontent.com/31321275/165968710-5ce07ab1-70c6-4acd-915b-c785c2f8b8b4.jpg)
Also of note, prior to the event I can export all entries into a spreadsheet for guest checkin.

Thank -- GT.

**Comment by hlthomps** [comment]
Thanks, Greg. I just had my husband walk through the process so he could put fresh eyes on it, and I think we're good with both the form and confirmation email now. 
We can go ahead and replace the language/link on the NorwesFest landing page "Be the first to know when tickets go on sale…Sign up for our e-newsletter now!" with a PURCHASE TICKETS button linking to the form.

I do have one question on the confirmation for your purchase - it had the unit price of the daytime tickets as $1 each - was that something you manipulated on the back end to avoid running a full purchase right now? I want to make sure the unit price is actually set to $10 per ticket.
For aesthetics - would we be able to replace the large logo on top with some sort of banner graphic? If so, can you send me dimensions that would work for both desktop and mobile?

Thanks!

**Comment by trinitywebmedia** [comment]
Yes, I forgot to mention that for testing purposes I made the tickets $1. (The original price of $10 has been restored.)
I will add a button to /norwesfest
The ideal dimensions for a banner is 1600 x 800. Please leave ample whitespace of 100px around (top, bottom, sides) to make sure we serve up an image that works for all media queries and devices.

**Comment by hlthomps** [comment]
Hello,

We decided to change the name of the evening event to "Sunset Soiree" to reflect the more high-end direction we are going this year. Would you be able to update this on the ticketing form and the email response that is generated? Please let me know if you have any questions. Thank you!

Heather

**Comment by trinitywebmedia** [comment]
Heather -- This was done using a find and replace script I wrote. I know I have all the front-facing changes done, and I believe all the email changes are done. Please let me know if I missed anything. -- GT
