### ISSUE TITLE
NorwesFest Landing page (priority)

### ISSUE THREAD

**Issue by hlthomps** [trinitywebmedia/Norwescap-Tickets#122]
Good morning,

We need to create a new landing page for NorwesFest. Would it be possible to simplify the URL to just norwescap.org/norwesfest? We have an opportunity to promote the event through flyer distribution at a networking event tomorrow, so if it's possible to get this done today (Monday) that would be greatly appreciated.

I've attached a Word document with the desired text and proposed layout. Please note we are NOT married to the two column format if that creates challenges for a nice visual layout on both desktop and mobile. I just wanted to create the distinction between the details of the two events, but those can be stacked rather than in columns if needed. The two graphics are designed to display side-by-side on the desktop and hopefully stack nicely on the mobile view.

The NorwesFest logo, the two images, and the Sponsorship PDF are all attached. Please reach out with any questions.

Thank you,
Heather
[NorwesFest 2022 webpage language.docx](https://github.com/trinitywebmedia/Norwescap-Tickets/files/8555231/NorwesFest.2022.webpage.language.docx)
[NorwesFest 2022 Sponsorship Form - fillable.pdf](https://github.com/trinitywebmedia/Norwescap-Tickets/files/8555233/NorwesFest.2022.Sponsorship.Form.-.fillable.pdf)
![NorwesFest Logo - General](https://user-images.githubusercontent.com/83599303/165105581-7da81f5a-810b-4136-b8d8-0b1acb89dc8f.png)
![NWF Web Graphic 1 - Family Fun Day](https://user-images.githubusercontent.com/83599303/165105988-0d34b39d-317d-4a21-a020-eab696d98195.jpg)
![NWF Web Graphic 2 - Sunset Social](https://user-images.githubusercontent.com/83599303/165105989-21a4c8cb-c489-461f-a8fe-fb488cea807b.jpg)

**Comment by trinitywebmedia** [comment]
We can use that url. I'll have something done for you by the end of today. -- GT

**Comment by trinitywebmedia** [comment]
The page is built as per the document. The only thing I suggest is adding four images as a gallery from last year's event. If you have images, just send here and I will update. (I'll leave this ticket open as we may update the page.) -- GT
