### ISSUE TITLE
Urgent: Add Info to Site

### ISSUE THREAD

**Issue by cfrsnorwescap** [trinitywebmedia/Norwescap-Tickets#124]
https://norwescap.org/education/child-and-family-resource-services/

On the above website, please put the below info right under the Current Childcare Services Policies heading at the top of the list of linked items. 

**Register Now for 2022 Summer Youth Camp Providers Information Sessions**

**Department of Health, Youth Camp Safety Project
2022 Summer Youth Camp Operator Kickoff Meeting**
This session will cover a general overview of the Youth Camp Safety Standards regulations, compliance and operations. 
 
**Wednesday, April 27, 2022**
9:30 a.m. - 12:00 p.m.

[REGISTER NOW!](https://register.gotowebinar.com/rt/7637434688030976782)

___________________________________

**Department of Human Services, Division of Family Development
2022 NJ Summer Youth Camp Info Sessions**

Both sessions will cover the same topics, please register for the session that works best for you. Each session is two hours. You can join for the whole session or join for just for the information you are interested in.

**Friday, April 29, 2022
and 
Friday, May 6, 2022** 
1:00 p.m. - 2:00 p.m.: registering your camp to accept child care assistance
2:00 p.m. - 3:00 p.m.: camp grants

[REGISTER NOW!](https://dhs-nj-gov.zoomgov.com/webinar/register/WN_rVb14h47QmObs-drBFc73A)

**Comment by trinitywebmedia** [comment]
DONE -- GT
