### ISSUE TITLE
Provide User Access to Marketing Team

### ISSUE THREAD

**Issue by trinitywebmedia** [trinitywebmedia/Norwescap-Tickets#125]
Issue author/limited admin access to two (2) Norwescap usernames 
Test & provide access by Monday 5/9

**Comment by trinitywebmedia** [comment]
u: heatherthompson pw: IFLQvqjL)QyBHD!U4nllCtVk
u: dawnhartfelder pw: $0f6*O9(0j63*qIfgmlvBe8X

https://norwescap.org/wp-admin

This will grant you access to change pages/posts and create new pages/posts. If something looks out of the ordinary or if you are unfamiliar with something, please let me know via GIT or text. -- GT

**Comment by trinitywebmedia** [comment]
I am going to close this ticket. If you need to refer to passwords please let me know. -- GT

**Comment by hartfelderd** [comment]
Mine didn’t work. ☹

**Comment by trinitywebmedia** [comment]
Dawn -- new pw:

Czi^@J^c0CII3Q9Y#^GERwJO

I just logged in and it worked fine for me. 

Also, can you please go to: ipchicken.com and let me know your IP Address so I can whitelist to prevent any other problems. Thanks -- GT

**Comment by hartfelderd** [comment]
It shut me down… It has definitely been two hours since I tried last…. ☹

& this is what that ipchick said:
173.3.223.180

**Comment by trinitywebmedia** [comment]
Dawn -- please try again, I whitelisted your IP address.

**Comment by hartfelderd** [comment]
***@***.***

Still hates me.

But I did successfully login AS HEATHER! (so… un… fair… lol)

**Comment by trinitywebmedia** [comment]
Dawn:
Try using your email address as the login with this new pw:

Pitl%Xff1quz$HQp9Q&gEnt8

**Comment by hartfelderd** [comment]
Greg…. I award you the “Heart of Patience” trophy for sticking in there with me! This time was a SUCCESS! You’re the best… 😉

**Comment by trinitywebmedia** [comment]
Awesome news. Here to help. -- GT

**Comment by hlthomps** [comment]
Hello,

I received a message via "Contactus" yesterday (5/25) at 10:55am saying that my password had been changed, and now I am no longer able to access Wordpress using the password provided above. I am not sure what triggered this, but I am hoping access can be restored so we can continue to update our NorwesFest page and other necessary content. 

Thank you,
Heather

**Comment by trinitywebmedia** [comment]
Heather --  I am out of the office until Tuesday. I will re-open this ticket and put more information re: this matter when I return. Thanks -- GT

**Comment by trinitywebmedia** [comment]
I am working through some access issues with the site being updated to WP 6.0 -- our role management system had a conflict and I will resolve shortly

**Comment by hlthomps** [comment]
Thanks, Greg. Any update to this? I tried again logging in with the password you had provided but no dice. I assume our passwords will change going forward?

**Comment by trinitywebmedia** [comment]
Heather -- I will look at this as soon as I can. Thanks -- GT

**Comment by trinitywebmedia** [comment]
We are no longer able to accomodate access to the site. -- GT

**Comment by hlthomps** [comment]
Greg, may I ask why we are no longer able to access the site as editors? Did something change with the upgrade to Wordpress 6.0 as you had mentioned previously?

Given this, I assume we should go back to the ticketing system to submit changes and edits to the site, and you will make them on your end? We will need to continue making updates to the NorwesFest page to add new sponsor logos, etc.

Thank you,
Heather

**Comment by trinitywebmedia** [comment]
** COPIED FROM EMAIL **

Good morning Heather -

There was a conflict with our user role management system, which stripped away access. When looking into it, we came to the conclusion that we are not willing to have outside users introduce content or code to the site's infrastructure with Trinity assuming all risk to the site's integrity when handing over files to Stephen prior to or on 8/13/22.

Please continue to post all requests to GIT and they will be handled within two-business days as per contract.

Thanks,
Greg
