### ISSUE TITLE
Add Doc to Site

### ISSUE THREAD

**Issue by cfrsnorwescap** [trinitywebmedia/Norwescap-Tickets#126]
https://norwescap.org/education/child-and-family-resource-services/

On the above website, please link the file attached and label "2022 Summer Youth Camp Grant Announcement" and please put it under the "Current Childcare Services Policies" heading. Thank you!

[FINAL 2022 Summer Youth Camp Grant Announcement.pdf](https://github.com/trinitywebmedia/Norwescap-Tickets/files/8661657/FINAL.2022.Summer.Youth.Camp.Grant.Announcement.pdf)

**Comment by trinitywebmedia** [comment]
DONE -- GT
