### ISSUE TITLE
Edit to Site

### ISSUE THREAD

**Issue by cfrsnorwescap** [trinitywebmedia/Norwescap-Tickets#127]
https://norwescap.org/education/child-and-family-resource-services/

On the above website, under the Current Childcare Services Policies heading, please take out the following information that is there:

Register Now for 2022 Summer Youth Camp Providers Information Sessions

Department of Health, Youth Camp Safety Project
2022 Summer Youth Camp Operator Kickoff Meeting
This session will cover a general overview of the Youth Camp Safety Standards regulations, compliance and operations.

Wednesday, April 27, 2022
9:30 a.m. – 12:00 p.m.

[REGISTER NOW!](https://register.gotowebinar.com/rt/7637434688030976782)

**Comment by trinitywebmedia** [comment]
DONE -- GT

**Comment by trinitywebmedia** [comment]
DONE -- GT
