### ISSUE TITLE
HOME PAGE

### ISSUE THREAD

**Issue by hartfelderd** [trinitywebmedia/Norwescap-Tickets#128]
On our HOME PAGE, please insert the enclosed GIF (HOME PAGE NorwesFest 625 × 332 px) UNDER the "Get Involved" and "Get Assistance" buttons, & ABOVE the "Meet Carrie Ann" section with an anchor to the page: https://norwescap.org/norwesfest/ 
![HOME PAGE NorwesFest 625 × 332 px](https://user-images.githubusercontent.com/103696465/168619014-d036c024-3df8-48c9-934a-1d73f615f7e5.gif)

**Comment by trinitywebmedia** [comment]
DONE. Thanks -- GT
