### ISSUE TITLE
Add Button To Home Page

### ISSUE THREAD

**Issue by hartfelderd** [trinitywebmedia/Norwescap-Tickets#129]
On the Home Page, in-between the button "Get Involved" and "Get Assistance", please insert a button that says "NorwesFest Tickets" that links to page: https://norwescap.org/norwesfest/ - this button should be a bright blue color.

**Comment by trinitywebmedia** [comment]
Stop putting tickets in before 8am...

**Comment by trinitywebmedia** [comment]
I'll take care of these right now.

**Comment by trinitywebmedia** [comment]
DONE -- GT
