### ISSUE TITLE
NorwesFest Form

### ISSUE THREAD

**Issue by KasiaWM** [trinitywebmedia/Norwescap-Tickets#13]
Hey Guys, 
The form doesn't exactly follow what was requested.  Please update the following.
Optional phone number and mailing address

Reinforce what is included in Family Fun Day and Adult:

Fun Day-  All-Inclusive: Gourmet Food - Pony Rides- Hay Rides- Pick Your Own- Music- Beer & Wine & More...
Sunset Social Affair-  All-Inclusive: Gourmet Food - Beer & Wine - 17 Piece Jazz Band - Picnic Blanket- & More
All In Pass- 
Conditional Formatting Logic

> - Choose the number of adult tickets / Kids
> - Adult 1 Name & Drop Down Meal Choice
> - Adult 2 "
> - Kid 1 Name and show meal (cream cheese is not going to fly with the kids can you please remove that from the sandwich?)

This is important as we have to know which person is getting which meal (food safety/ allergy issue). 

Also we don't need to list out a price at $0.00 ... don't list a price at all. 

After the ticket is purchased do they automatically get an email? Can you shoot us over a screen shot of what that looks like?

**Comment by trinitywebmedia** [comment]
I will review this tomorrow and make the adjustments that are possible. Some of your requests cannot be accommodated.

@keberletwm  -- let's discuss today and maybe contact Norwescap to make sure we are clear in direction. -- GT

**Comment by KasiaWM** [comment]
Cool if you guys think its easier to jump on a call the three of us to just brainstorm this I'm freer this morning.  Then we can confirm everything in writing in Github. Totally up to you.

**Comment by trinitywebmedia** [comment]
@keberletwm Can you please facilitate a call and get what I need to re-design the form. Depending on the re-design, there may be additional dev hours required. 

Post call I will review with you and create a timeline for the changes. -- GT

**Comment by KasiaWM** [comment]
@keberletwm I'm available now, can we do a quick google meet or zoom?  I know we are on a deadline and I want to make sure Greg has everything he needs.

**Comment by KasiaWM** [comment]
Hey any updates?

**Comment by trinitywebmedia** [comment]
This should be done by the morning -- GT

**Comment by KasiaWM** [comment]
![Copy of Website](https://user-images.githubusercontent.com/83297632/118877845-eaf1a700-b8bc-11eb-8780-411f7ed29958.png)


Image... Copy next

**Comment by trinitywebmedia** [comment]
I think this is in the wrong ticket -- please add to Covid changes -- GT

**Comment by KasiaWM** [comment]
Will do. On and the button on the homepage can you change to NorwesFest instead of NorwesTFest Info?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by trinitywebmedia** [comment]
This is done and can be reviewed -- GT

**Comment by trinitywebmedia** [comment]
Please make notes on the appropriate tickets, or else critical instructions will be missed. -- GT
