### ISSUE TITLE
Add info to site

### ISSUE THREAD

**Issue by cfrsnorwescap** [trinitywebmedia/Norwescap-Tickets#132]
https://norwescap.org/education/child-and-family-resource-services/

On the above website, please enter the following message below the linked documents under the "Current Childcare Services & Policies" heading:

**Re-opening of the NJ ARP Stabilization Grant** 
Applications will be accepted from June 6, 2022 through July 8, 2022!
 
This round of the ARP Stabilization grant is open to new licensed or registered providers who opened after March 11, 2021.  If you need funds to help cover your operational expenses through August 2023 – APPLY beginning June 6!  Just log in to your [NJCCIS account](http://www.njccis.com/) and navigate to the Grants tab from your Quicklinks panel.
 
Applying is quick and easy with grants up to $120,000 waiting for you.
 
For more information and How-To Videos and Documents, visit the [ChildCareNJ.gov NJ ARP Stabilization Grants page](https://www.childcarenj.gov/Providers/Grants/ARPStabilizationGrant).

**Comment by trinitywebmedia** [comment]
DONE -- GT
