### ISSUE TITLE
Take out Info on Site

### ISSUE THREAD

**Issue by cfrsnorwescap** [trinitywebmedia/Norwescap-Tickets#133]
https://norwescap.org/education/child-and-family-resource-services/

On the above website, please take out the following information that is located below the "Current Childcare Services & Policies" section:

Department of Human Services, Division of Family Development
2022 NJ Summer Youth Camp Info Sessions

Both sessions will cover the same topics, please register for the session that works best for you. Each session is two hours. You can join for the whole session or join for just for the information you are interested in.

Friday, April 29, 2022
and
Friday, May 6, 2022
1:00 p.m. – 2:00 p.m.: registering your camp to accept child care assistance
2:00 p.m. – 3:00 p.m.: camp grants

[REGISTER NOW!](https://dhs-nj-gov.zoomgov.com/webinar/register/WN_rVb14h47QmObs-drBFc73A)

**Comment by trinitywebmedia** [comment]
DONE -- GT
