### ISSUE TITLE
Updates to NorwesFest page

### ISSUE THREAD

**Issue by hlthomps** [trinitywebmedia/Norwescap-Tickets#134]
Hello,

Can you please make the following updates to https://norwescap.org/norwesfest/ - 

Delete duplicate paragraph that begins with "All funds raised from NorwesFest will support Norwescap’s mission..."

Underneath this paragraph, Add "**Check out our `photo album` from NorwesFest 2021**" - "photo album" should link to https://www.flickr.com/photos/195544633@N05/sets/72177720299038693/ 

Underneath the last sentence before the Sponsor logos section, add " _Rain Date: Sunday, June 26_ "

Add all attached logos at the bottom of the page in the "In Partnership With" section. The particular order is not important, lay out however it looks best. They can be sized down so the entire section does not end up looking too overwhelming. 

If you have any questions please let me know. Thanks!
![Bourbon Street Wine   Spirits](https://user-images.githubusercontent.com/83599303/173671882-ffa88597-6206-45f4-9cb4-4359efa8cfd2.jpg)
![CofferPotterLogo](https://user-images.githubusercontent.com/83599303/173671924-34581d60-3f56-40e9-9f8f-b41d96f869cd.png)
![Summer Swing Orchestra](https://user-images.githubusercontent.com/83599303/173672069-7196d61d-0168-4779-99f5-e27d3e9ff274.png)
![Two Chicks](https://user-images.githubusercontent.com/83599303/173672071-d1c54ed5-2d14-4f31-9c73-d44410bafc9e.jpg)
![Yummy Bakes by Jo](https://user-images.githubusercontent.com/83599303/173672072-b8712a92-fd10-4dd2-b2b4-58fb610638d6.png)
<img width="150" alt="Gelotti_NJ" src="https://user-images.githubusercontent.com/83599303/173672073-1dd3643a-7757-4b6f-bef1-912e19bcfa53.png">
![Invertase Brewing](https://user-images.githubusercontent.com/83599303/173672075-024f3078-64de-4988-bbb6-906b9fa577ae.png)
![offwhite-circle - Flounder Brewing](https://user-images.githubusercontent.com/83599303/173672076-8df9b178-e499-4403-ab3c-b396a87e2e89.jpg)
![OMealia_Logo](https://user-images.githubusercontent.com/83599303/173672078-ee2faf63-1784-46a3-9d47-888b4188780c.jpg)
![Penelope_Logo_WEB_RGB_Color - Michael Paladini](https://user-images.githubusercontent.com/83599303/173672081-6dcce1e0-198a-4973-8926-6173d14b53ab.png)
![Sourland Mountain Spirits](https://user-images.githubusercontent.com/83599303/173672083-7bbc3427-7bcd-403b-a689-ee1f8ca8b12c.jpg)

**Comment by trinitywebmedia** [comment]
Done -- GT
