### ISSUE TITLE
Website document upload needed

### ISSUE THREAD

**Issue by cfrsnorwescap** [trinitywebmedia/Norwescap-Tickets#135]
https://norwescap.org/education/child-and-family-resource-services/

On the above website, please upload the attached document under the heading “Current Childcare Services and Policies” and label it as “Enrollment-Based Payment Extension Notice” please.  

[DFDI 22-06-01 -- Attachment Enrollment-Based Payment Extension Notice. Norwescap.pdf](https://github.com/trinitywebmedia/Norwescap-Tickets/files/8919152/DFDI.22-06-01.--.Attachment.Enrollment-Based.Payment.Extension.Notice.Norwescap.pdf)

**Comment by trinitywebmedia** [comment]
DONE - GT
