### ISSUE TITLE
Update to Food Bank summer feeding program post

### ISSUE THREAD

**Issue by hlthomps** [trinitywebmedia/Norwescap-Tickets#136]
Hi,

Can you please make the following updates on the blog post https://norwescap.org/news-events/norwescaps-food-bank-summer-food-service-program-now-open/:

Change subtitle to "Free lunch for children up to Age 18!" (removing grab-and-go)
Change dates to "June 20 - August 19, 2022"
Change first paragraph below location listings to "When school closes in June, many children lose their only reliable source of food. Norwescap's Food Bank hosts a federally funded Summer Food Service Program in Phillipsburg, New Jersey, providing free nutritious lunches to children up to the age of 18, Monday through Friday during late June, July and August. More than 4,000 free lunches are provided to Phillipsburg children and youth each summer through this program."
Delete 2nd paragraph sentence that begins "Through this program, during the summer of 2019..."

Note - I know it's not ideal to update a past blog post - but Helene has already provided this URL to some partners to link for information for our summer feeding program, so I want to make sure the updated info is reflected here. Please let me know if you have any questions. Thank you.

**Comment by hlthomps** [comment]
Apologies, I missed one change:

Right under "Walk in Sites:" Please add in italics
_All lunches must be eaten on the premises. Meals cannot be taken to go._

**Comment by trinitywebmedia** [comment]
DONE - GT

**Comment by hlthomps** [comment]
Thank you! Just one thing, can you please delete the sentence "Through this program, during the summer of 2019 over 4,000 free lunches were provided to children at several locations in Phillipsburg."
