### ISSUE TITLE
Report for NorwesFest tickets

### ISSUE THREAD

**Issue by hlthomps** [trinitywebmedia/Norwescap-Tickets#137]
Hello,

Can you please send a report of everyone who has purchased tickets to Norwesfest so far? We have been logging each one as we receive the email confirmations, but several people have contacted us claiming to have purchased tickets and we do not have them on record. We want to be sure we haven't missed anyone who has purchased through the site.

Thank you,
Heather

**Comment by trinitywebmedia** [comment]
Here is an export of all fields from from the NorwesFest Ticketing site. Thanks. - G
[tickets-2022-2022-06-21.csv](https://github.com/trinitywebmedia/Norwescap-Tickets/files/8948096/tickets-2022-2022-06-21.csv)
T
