### ISSUE TITLE
Additional updates to NorwesFest page

### ISSUE THREAD

**Issue by hlthomps** [trinitywebmedia/Norwescap-Tickets#138]
Please make the following text updates to https://norwescap.org/norwesfest/:

Update text at top to the following (please keep current formatting, change the text only):

**Summer is officially here - and NorwesFest 2022 is just a few days away! Join us THIS Saturday, June 25 at Ort Farms!

This two-in-one event has something for everyone – whether you’re looking for a fun day on the farm with your family, or an elegant night out under the stars with your spouse, partner, or friends!

ONE DAY, TWO EVENTS – you’ll find it all at NorwesFest. Reserve your tickets TODAY and avoid the lines on Saturday!**

Please add in italics underneath the first "Buy Tickets" button, above the photos:

**Please note that tickets may ONLY be purchased through Norwescap. If you have purchased tickets and you are not able to attend, please contact us at (908) 454-7000 x1107 for a refund.**

Please update the text under the Family Fun Fest image to:

Want to get out with the family to spend the day at one of New Jersey’s best farms? NorwesFest’s Family Fun Day offers an experience you and the kids won’t forget! The day will be packed with games and activities, including pony rides, hay rides, carnival games, sports, face painting, treasure hunts, pick-your-own, and more – **all included with your $10 ticket!** Snacks and soft drinks are included, and adults will enjoy wine and beer tastings; lunch and treats will be available for purchase on site from local food trucks. 

Let me know if you have any questions. Thanks!

**Comment by trinitywebmedia** [comment]
I'll have this done by Thursday Noon at the latest. Thx -- GT

**Comment by hlthomps** [comment]
Hi Greg - while you're working on these changes - can you please add a link "Frequently Asked Questions" with a link to the attached PDF, underneath the first "Buy Tickets" button (but above the language we're adding that starts with "Please note that tickets...")

Any questions, let me know. Thanks!
[NorwesFest 2022 FAQs.pdf](https://github.com/trinitywebmedia/Norwescap-Tickets/files/8969266/NorwesFest.2022.FAQs.pdf)

**Comment by trinitywebmedia** [comment]
Done. Thanks -- GT
