### ISSUE TITLE
HomePage- Events Button

### ISSUE THREAD

**Issue by KasiaWM** [trinitywebmedia/Norwescap-Tickets#14]
Can we please replace the Events button here with NorwesFest Tickets? and link to the page https://norwescap.org/news-events/norwesfest-2021/?  
It should look similar to the Get Help Now Button and the Get Involved button but be sky blue
Norwescap Sky Blue
PMS: 299
CMYK: 86/8/0/0
RGB: 0/163/224
HEX: #00A3E0

![Events tab](https://user-images.githubusercontent.com/83297632/118735925-61d06680-b80f-11eb-87a7-8dcdab0b8d63.png)

**Comment by trinitywebmedia** [comment]
Thank you for the Hex colors. DONE -- GT
