### ISSUE TITLE
Web-Site Update - https://norwescap.org/norwesfest/

### ISSUE THREAD

**Issue by hartfelderd** [trinitywebmedia/Norwescap-Tickets#141]
Save the Date: To Be Determined, 2023
Ort Farms | 25 Bartley Road, Long Valley, NJ
11am-3pm Family Fun Day  |  5:30-9pm Sunset Soiree

NorwesFest 2022 was a blast! On Saturday, June 25 at Ort Farms, we enjoyed a truly fantastic day – and evening – at our second annual NorwesFest.

Thank you so much for your support with this event. We are so grateful to every one of you who attended, brought your friends along, donated, sponsored, bought raffle tickets, shared the news on social media, or took part in any way. Not only did you fill the day with energy and fun, but you helped us reach a new fundraising high – more than $60,000 raised to support our neighbors as they work to overcome obstacles and achieve their dreams!

As we look through these photos, we can’t stop smiling, and hope the same for you. Browse through our Flickr album here for high-quality images ready to be downloaded for your sharing:
 https://www.flickr.com/photos/195544633@N05/sets/72177720300147064/, 

Or scroll through the Facebook album and tag yourself - or friends and family - when you spot your picture, and share the love and energy through the power of pictures:
https://www.facebook.com/media/set/?vanity=Norwescap&set=a.403205911853601

These photos were taken by the super talented and skilled: Cathy Miller in Hunterdon County.

For us to bring you events like this that help the Norwescap mission of creating opportunities to change the lives of tens of thousands of individuals and families in our community we need your feedback. Please take 5 minutes to complete this guest survey: 
https://forms.office.com/r/T5BywZKp0E

We are already discussing our ideas and plans to make NorwesFest 2023 even better, and hearing back from you will help us establish NorwesFest as THE premiere family event and fundraiser of the season – one we hope you will look forward to attending each and every year.

We must again thank our generous event sponsors: ShopRite; Mutual of America; NJM Insurance; Valley National Bank; PNC Bank; and Provident Bank for not only supporting the event, but sending an INCREDIBLE, energetic group of volunteers; and all our other sponsors who made the event possible. Because of their generous support, 100% of the funds raised through ticket sales, raffle and donations go straight to our mission. Now that is something we can all feel great about!

(KEEP THE BAR OF IMAGES OF THE SPONSOR LOGOS HERE)

Thank you again, and I hope you see you next June at Ort Farms, if not sooner!

If you’re interested in being a part of NorwesFest planning, or supporting Norwescap in any other ways, contact our Chief Development Officer, Heather Thompson, at [thompsonh@norwescap.org](mailto:thompsonh@norwescap.org) or call us at (908) 454-7000 x1106.

The Family Fun portion of NorwesFest happened from 11 am to 3 pm with a ticket price of only $10 per person. Children under 2 were admitted free. This day offered a great way to get out with the family to spend the day at one of New Jersey’s best farms. NorwesFest’s Family Fun Day offered an experience you can’t forget - packed with games and activities, including pony rides, hay rides, carnival games, sports, face painting, treasure hunts, pick-your-own, snacks and soft drinks, wine and beer tastings for the adults, and more – all included with the $10 ticket! Additional lunch and treats were available for purchase on site from local food truck: Homer’s Girls. 

The evening, from 5:30 to 9:00 pm, of NorwesFest offered an elegant Sunset Soiree with an all-inclusive ticket for only $150 per person, age 21 and up. This event was a fabulous date night or celebratory evening out with friends. The Sunset Soiree had everything that an opulent summer party could include – a gourmet farm-to-table spread from appetizers to entrée to desserts; fine wines, craft brews, and cocktails from local distilleries; and live music by the SummerSwing Orchestra, a 17-piece band with singer Kevin Grey, that had us all up and dancing to, or at least tapping our toes with All happening in nature’s gorgeous outdoor space with the sun setting over the mountains as our evening’s backdrop. 

Every dollar raised from this all-inclusive benefit is supporting the Norwescap mission to create opportunities and change lives for more than 35,000 New Jerseyans each year. Your support of NorwesFest 2022 is helping us address our neighbors’ most urgent needs – like food, housing, childcare and education and career develpoment – and helping them work towards a future where they and their families can not only survive, but thrive!

[BUTTON: RSVP FOR 2023 TICKETS NOW](was https://norwescap.org/norwesfest - but make new link to EMAIL TO [thompsonh@norwescap.org](mailto:thompsonh@norwescap.org)) 

[2022 SPONSORSHIP FORMS (PDF)](https://norwescap.org/wp-content/uploads/2022/04/NorwesFest.2022.Sponsorship.Form_.-.fillable.pdf)
 - (Keep it the same link)

NorwesFest makes wonderful memories while making a difference in your community. We are so happy and grateful to have you there!

FORMATTED SIMILAR OR AS:
[22.07.06 - NorwesFest Wrap Up - Gratitude and RSVP for 2023.docx](https://github.com/trinitywebmedia/Norwescap-Tickets/files/9057127/22.07.06.-.NorwesFest.Wrap.Up.-.Gratitude.and.RSVP.for.2023.docx)

**Comment by trinitywebmedia** [comment]
DONE - GT

**Comment by hartfelderd** [comment]
The top part looks great! Thank you so much! Re-buttonized (if that’s a real word… lol), thank you for fixing that.

Just below that though… we really don’t need the link to the NorwesFest page on the home page anymore. (See enclosed image)

(Soon… I’ll send over some super fun Somerset Patriots Baseball Game info to put up there!)

😊 Dawn

*OH… and I love the NorwesFest page update too! (#141) Looks lovely! 😊
