### ISSUE TITLE
New Blog Post... 

### ISSUE THREAD

**Issue by hartfelderd** [trinitywebmedia/Norwescap-Tickets#142]
Please post the content from the attached Word document as a new blog post, using the title "Norwescap Named Central Jersey Hub of The Regional ACEs Collaborative ". A photo is attached as well. Please let me know if there are any questions or issues. Thank you!
[22.07.14 - ACE's and the RAC.docx](https://github.com/trinitywebmedia/Norwescap-Tickets/files/9113326/22.07.14.-.ACE.s.and.the.RAC.docx)
![2022 07 14 - Blog RAC - (564 × 212 px)](https://user-images.githubusercontent.com/103696465/179024354-532c1c37-dfc7-4a8f-bbe2-65bfa42f3cf1.png)

**Comment by trinitywebmedia** [comment]
Thank you. I will have this done by Monday noon. -- GT

**Comment by trinitywebmedia** [comment]
DONE -- GT

**Comment by hartfelderd** [comment]
I still am not seeing this page (BLOG POST) on the site… can you check this for me?

😊 Dawn

**Comment by trinitywebmedia** [comment]
Clear your cache -- GT
<img width="1266" alt="Screen Shot 2022-07-19 at 2 09 24 PM" src="https://user-images.githubusercontent.com/31321275/179819758-828c0c22-4fc2-49b3-9e9f-7de24e3fb5ef.png">
e
