### ISSUE TITLE
childrens tickets

### ISSUE THREAD

**Issue by KasiaWM** [trinitywebmedia/Norwescap-Tickets#16]
Hey can we please take a moment and change the kids age for tickets. replease 12 and under with 2-16  
and add Infants FREE.
Thanks.

**Comment by trinitywebmedia** [comment]
I assumed this says replace 12 and under with 'ages 2-16' and added 'Infants Free' the only I could for that field

**Comment by KasiaWM** [comment]
yup...thats exactly what it says. Thanks for translating.
