### ISSUE TITLE
NorwesFest Tickets discount

### ISSUE THREAD

**Issue by KasiaWM** [trinitywebmedia/Norwescap-Tickets#19]
Hey guys can you please add a discount code area?

THe code should be NorwesFestFriend

rates discounted to the following rates

day rate adult $50
child no discount

all-day adult $125

Adult night $100

**Comment by trinitywebmedia** [comment]
I will look into this when back in the office. Not sure how long this will
take, but we are out of dev hours until 6/15.

What ‘s the timeline? -- GT

**Comment by trinitywebmedia** [comment]
Please do not send out anything re: coupon code  'NorwesFestFriend' until we can figure things out. 
We need to alter to use multiple different codes or a straight pct. discount -- GT

**Comment by trinitywebmedia** [comment]
No response since ticket created. Left Heather v/m 10:45 Wednesday to get possible answer. Ticket closed for now -- GT

**Comment by KasiaWM** [comment]
One code will do. 
We will be giving it to friends and family.
-k

**Comment by trinitywebmedia** [comment]
Kasia -- I can't do one code to change all pricing to specific discounted prices. We either have to have multiple codes to accommodate each price discount or a straight pct discount off the total.



CODE ONE  change day rate adult to $50
CODE TWO all-day adult to $125
CODE THREE Adult night to $100

or - 20% on all items.

Please let me know how to proceed and what date this needs to be completed by. - GT

**Comment by KasiaWM** [comment]
OH I see what you mean.  Sorry, never done this before. Basically we can just say the 20% off

**Comment by trinitywebmedia** [comment]
Ok, is there any timeline here? Thx -- GT

**Comment by KasiaWM** [comment]
Yes as soon as humanly possible? Events next week so Hopefully we can hand it out over the weekend.

**Comment by trinitywebmedia** [comment]
Ok - Got it.

**SUMMARY:**

Coupon Code: NorwesFestFriend - 20% total checkout discount
Deadline: eod 6/17/21

**Comment by KasiaWM** [comment]
cool. 
thanks

**Comment by trinitywebmedia** [comment]
This is done. Coupon code 'NorwesFestFriend' gives a 20% discount off the transaction. The discount is notes as 'Friends and Family Discount' 

This task took 90 mins. (90 mins remain from 6/15 - 7/15) -- GT
