### ISSUE TITLE
Volunteers Page

### ISSUE THREAD

**Issue by KasiaWM** [trinitywebmedia/Norwescap-Tickets#20]
[Volunteer Website Changes.docx](https://github.com/trinitywebmedia/Norwescap-Tickets/files/6695419/Volunteer.Website.Changes.docx)

Hey Greg,
need some help with the volunteer's page.  I do not have time to address this fully since I knee deep with NorwesFest.  Can you take a look please and tell me how many dev hours this will take to do?  We need to get it done by July 1.  So if this is something that is extensive for any reason, I just need to figure out how to address finanicially if it doesn't fit into dev hours...
thx

**Comment by trinitywebmedia** [comment]
Thank you for the message. I will look at this doc today and send over thought and/or questions. -- GT

**Comment by KasiaWM** [comment]
Thanx. I will try to monitor this, but if you absolutely do not hear from me call my cell 9083289797

**Comment by trinitywebmedia** [comment]
Can you please send the Volunteerism icon here. These changes are not too bad. We have 90 minutes left foo 6/15 - 7/15 ::: I think I can get this done within that time. -- GT

**Comment by KasiaWM** [comment]
Hopefully this one will work. 
I tried to upload the AI but the file isn't supported in the system. This is hopefully a high res png. 
-K
![Volunteerism](https://user-images.githubusercontent.com/83297632/122988891-3a217080-d370-11eb-82e2-dfa3fe450807.png)

**Comment by trinitywebmedia** [comment]
This was done a while ago...sorry I did not close the ticket. -- GT
