### ISSUE TITLE
Routing Issue

### ISSUE THREAD

**Issue by KasiaWM** [trinitywebmedia/Norwescap-Tickets#21]
Kasia,

As discussed, we learned today that the hyperlink on the "Get Help Now" form on our homepage is pointing to the Contact Us page. This has resulted in an uptick of people just sending an email message to Maritza instead of going through our intake process. Please get this fixed ASAP as it is creating a customer service issue with our participants. 

The "Get Help Now" button should link to:
https://portal.empoworbycsst.com/Public/ClientAccessForm.aspx?AccessID=51efa030-cd09-48eb-9e7d-93b00c218be2

**Comment by trinitywebmedia** [comment]
Was this discussed with us and we missed it? I will have this changed. -- GT

**Comment by KasiaWM** [comment]
No you guys didn't miss it. It went unnoticed by everyone. All of a sudden Martiza was getting an influx of emails to get help and no one was going through empower so they figured something went to shit.

**Comment by trinitywebmedia** [comment]
Homepage Link Fixed. -- GT
