### ISSUE TITLE
Norwesfest Wrap Up

### ISSUE THREAD

**Issue by keberletwm** [trinitywebmedia/Norwescap-Tickets#23]
Hey Kasia,

We have a few questions in order to wrap up our end of Norwesfest.

1. When should we disable the ability to order tickets through the website?
2. When do you need data exported by and who should we send to?

Thanks!

**Comment by KasiaWM** [comment]
1:30 am
Data exported by tomorrow morning 10 am. Heather and Myself will do.

**Comment by keberletwm** [comment]
Kasia,

This would need to be done manually. 1:30 AM is not practical. We can remove the purchase tickets button now or as soon as we are in the office tomorrow. Please let me know which works better for you.

**Comment by KasiaWM** [comment]
Okay.. first thing in the morning

**Comment by trinitywebmedia** [comment]
Save The Date Popup removed
Ticket buttons removed from LP
RSVP Data export attached

[data-norwesfest-tickets-2021-06-25.xlsx](https://github.com/trinitywebmedia/Norwescap-Tickets/files/6716036/data-norwesfest-tickets-2021-06-25.xlsx)
