### ISSUE TITLE
Patrick/ Peggy Website Issues

### ISSUE THREAD

**Issue by KasiaWM** [trinitywebmedia/Norwescap-Tickets#24]
. The Web site is a mess in terms of finding things including the loss of the “Jobs” button that used to be on the “Home” page. 

After an extensive search for information that I know was at one time on the web site I came across a link to the Jobs section of the site under the “Leadership Profiles” page. There are a lot of links to News & Articles of interest located there that have nothing to do with the “Leadership Profiles” (of which there is only Mark’s). 

Additionally on that “Profiles” page there is a link to “Jobs Filled” and the listed position is for “Substitute” positions that are never filled. 

Finally, when Peggy adds a posting on the backend we are supposed to get a notification from Trinity that the position is ready to publish. Well, sometimes that happens and sometimes it just gets published and we only know it is up by going to look for it on the web page. Things that have recently been added are not getting readied for publication and there are parts that have been edited or moved from the back end section by others. 

As I am reviewing my open job postings on our website, I notice that the option is now missing from the bottom of the page.  Can you please tell me how to find the open Norwescap positions?

**Comment by trinitywebmedia** [comment]
Kasia -- I will look at this note today. Kevin will be in contact with you to discuss in detail what you want where, so we can clean up this mess. -- GT

**Comment by KasiaWM** [comment]
GT- Thanks. Send help and Vodka.
Kevin- please call Peggy regarding these issues. 
Fill me after you speak to her.

**Comment by trinitywebmedia** [comment]
Hang in there, we will get this sorted out. - GT

**Comment by keberletwm** [comment]
Spoke with Peggy this morning to better understand the issues she is experiencing. 

1. The Employment Opportunities Link is no longer on the bottom of the Home Page or the rest of the site

2. Notifications when submitting job postings have been sporadic

3. Emails for Routing applications are not carrying over to the published posts. Peggy must go in and edit manually.

4. Categories are showing on bottom left sidebar of Leadership Profiles Page

**Comment by trinitywebmedia** [comment]
I will look at these items today and resolve -- GT

**Comment by trinitywebmedia** [comment]
NOTES:
**The Employment Opportunities Link is no longer on the bottom of the Home Page or the rest of the sit**e -- LINK IS BACK ON BOTTOM OF HOME PAGE

**Notifications when submitting job postings have been sporadic** -- Peggy is on the email list. It either works or it does not, it's not a sporadic thing. 

**Emails for Routing applications are not carrying over to the published posts. Peggy must go in and edit manually.** -- ADDED - Previously this was not wanted on the page

**Categories are showing on bottom left sidebar of Leadership Profiles Page** -- FIXED

@keberletwm Can you please follow up with Peggy and let her know that this is taken care of. If there are any other issues re: Job Posting, please file an additional ticket.
