### ISSUE TITLE
Patrick & Peggy Round 2....

### ISSUE THREAD

**Issue by KasiaWM** [trinitywebmedia/Norwescap-Tickets#25]
•	the backend Job Posting process is stripping the email address for applicants to reply to. This means that Peggy has to go back into the back side and edit the post once published so to add that email link back into the post;
•	if you use the Search function at the top of the page and put in “Jobs” you get a variety of things from random Job Posting to articles about all sorts of things that seem unrelated to employment. If you put in that space “Employment” then you get to the main Job Posting page; 
•	when you hover over the “News” tab at the top of the Home Page it highlights Covid-19 Resources but if you click on it you get a variety of stories about all kinds of things

**Comment by trinitywebmedia** [comment]
**• the backend Job Posting process is stripping the email address for applicants to reply to. This means that Peggy has to go back into the back side and edit the post once published so to add that email link back into the post;** -- I BELIEVE THAT WAS ADDRESSED EARLIER, BUT I WILL TEST THIS AFTERNOON


**• if you use the Search function at the top of the page and put in “Jobs” you get a variety of things from random Job Posting to articles about all sorts of things that seem unrelated to employment. If you put in that space “Employment” then you get to the main Job Posting page; --** NOTHING WE CAN DO ABOUT THAT. WE USE THE WORDPRESS SEARCH QUERY THAT PULLS ALL INFO W/ THE SEARCH TERM


**• when you hover over the “News” tab at the top of the Home Page it highlights Covid-19 Resources but if you click on it you get a variety of stories about all kinds of things** THIS IS NOW CHANGED TO ONLY PULL THE 'NEWS' CATEGORY. PLEASE ADVISE WHOMEVER IS POSTING TO THE SITE TO USE THE PROPER CATEGORY.

**Comment by trinitywebmedia** [comment]
Email field displays on post
