### ISSUE TITLE
Account Suspended

### ISSUE THREAD

**Issue by keberletwm** [trinitywebmedia/Norwescap-Tickets#26]
The Norwescap Website is currently showing as account suspended

Received call from KM

**Comment by trinitywebmedia** [comment]
This does not look like a LW or Trinity issue. These are not the previous nameservers or ones we use. -- GT

<img width="1088" alt="Screen Shot 2021-07-22 at 12 40 24 PM" src="https://user-images.githubusercontent.com/31321275/126676343-359f43cb-9b12-4ad8-9f62-8c7139bd1e42.png">

**Comment by trinitywebmedia** [comment]
Without visibility to the registrar, I believe the Nameservers and other records were changed at the registrar and the previous A record of 67.225.191.10 was removed or changed. 

TWM DNS is always ns.liquidweb.com and ns1.liquidweb.com -- GT

**Comment by trinitywebmedia** [comment]
Site is backup. It looks like something between the registrar and the hosting security changed.  We removed more malware off of site from previous infection(s) and we are good as of now.
