### ISSUE TITLE
SITE SECURITY FROM PREVIOUS PLUGIN HACK

### ISSUE THREAD

**Issue by trinitywebmedia** [trinitywebmedia/Norwescap-Tickets#27]
Due to the previous hack of our server from a deprecated plugin and imported code all access is limited to the site. This hack has now impacted every Trinity Web Media. Further server cleanup and security is being evaluated and configured.  -- GT

**Comment by trinitywebmedia** [comment]
We are now doing a full server restore. This means we are losing three days worth of work. Trinity and Norwescap needs to have a discussion on moving forward from here.

**Comment by KasiaWM** [comment]
Hey guys. Seeing this now. What is the best way to solve the issue? Cant login in to post anything to meet states deadlines. Thoughts?

**Comment by keberletwm** [comment]
7/27/2021 12:01 Spoke to KM about the ongoing issues. She understands we will be in contact once the website has been restored posting can be resumed.

**Comment by trinitywebmedia** [comment]
I do not see access being restored to the site any time soon. We need to discuss with Mark and Steve how security is  handled moving forward, plus associated costs for the 60+ hours lost due to Norwescap making our server vulnerable. 

I do not think you have any idea the situation Norwescap put our comapany in-- GT

**Comment by KasiaWM** [comment]
GT- I sent an email to Mark and Steve about the vulnerabilities.  Do you have any recommendations or solutions to mitigate the issue? I can schedule time for us to talk and go through the recommendations/ solutions.

**Comment by trinitywebmedia** [comment]
We are currently drafting an email for Mark and Steve to let them know the impact. As of now, I have no solutions to offer until I hear from the security team and our entire company is restored. I do not see this being resolved today, and possibly this week.

From there, I think it's best we schedule an in person meeting with Mark and Steve. -- GT

**Comment by KasiaWM** [comment]
Please copy myself and Heather on the email as well.  
In person or via zoom? Zoom may work better for scheduling and coordinating all of our schedules.

**Comment by trinitywebmedia** [comment]
This needs to happen in person.

**Comment by KasiaWM** [comment]
On it.

**Comment by trinitywebmedia** [comment]
QUICK UPDATE: Site was restored to 7/24 server backup. Anything added from 7/24 to today is no longer on site.
Site was down for 50 minutes.

We are currently reviewing the malware log with the Security team and will keep everyone post once everything is resolved. 
Access is not being restored until after a security discussion and everyone is in agreement.

If there are any State mandated posts that need to go live this week, we can post them on-site for Norwescap at a charge after malware is removed.

I will update this ticket as I learn more. -- GT

**Comment by KasiaWM** [comment]
GT- meeting has been scheduled. As far as content updates go, we agreed that no one would mess around with anything on the site and we were restricted to only updating content.  There is no reason for you to post content updates when that is something we are capable of doing within the restrictions given. 

The discussion regarding maleware should not prohibit content updates.

**Comment by trinitywebmedia** [comment]
It absolutely will restrict content updates. For the foreseeable time, no one other than Trinity and our security team will have access to the site. This is non-negotiable. -- GT

**Comment by KasiaWM** [comment]
I can understand your frustration, but I am trying to understand why content updates are being restricted.  We did not in any way do anything out of line since this was discovered the first time around. We have only updated blogs, news and pages since as was discussed. 

I need to be able to explain why we aren't able to update the content.  How will us updating content impact the website?  What will be the difference of us doing the content updates vs. Trinity?  

I'm not arguing with you, I'm asking you the questions I need to answer.

**Comment by keberletwm** [comment]
Kasia,

Until this situation has been completely resolved we need to restrict site access to ensure absolutely all best practices are being followed. This issue has absolutely wreaked havoc on us as a company. Unfortunately, restricting access is the only way we can mitigate risk completely.

**Comment by KasiaWM** [comment]
Thanks.  I will let them know that because of the greater impact we need to contain the situation.  

As far as best practices, please have something we can distribute during the meeting.

**Comment by trinitywebmedia** [comment]
I will forward a best practice link for your review pre-conversation. This is not training meeting, but more of a meeting to determine whether or not we should continue to work together and come to an understanding as to the total impact your actions had on our company and clients.

**Comment by trinitywebmedia** [comment]
Norwescap site is down as of 10:12 am

**Comment by trinitywebmedia** [comment]
Steve reached out to Kevin re: site down and let him know we are working on it. -- GT

![Steve](https://user-images.githubusercontent.com/31321275/128041701-95616fde-0bcc-42cc-b52c-6880dd6d537a.jpg)

**Comment by trinitywebmedia** [comment]
wp-config.php file re-created and uploaded. Site is back online. 

Norwescap.org was down for approx 70 minutes. @keberletwm Please note for your meeting tomorrow -- GT

**Comment by keberletwm** [comment]
Norwescap.org is down again due to recurring issues from previous hack/vulnerability.

**Comment by trinitywebmedia** [comment]
Not stoked. I will look at it and see if I can get it back online or file a ticket with LW -- GT

**Comment by trinitywebmedia** [comment]
Closed by accident ^

**Comment by trinitywebmedia** [comment]
Two malware folder removed. (See Screenshot) WordPress reinstalled in the root folder through cPanel
![Screen_Shot_2021-08-03_at_6_53_25_PM](https://user-images.githubusercontent.com/31321275/128096673-80a675e5-4e2c-4eed-96ee-e3e9c05fd57a.jpg)

This is the same social engineering hack we have been dealing with on other sites. 

Site is back online.

**Comment by trinitywebmedia** [comment]
We need to add a layer of security for Norwescap to protect their liability from a larger database breach regarding donor personal information and encrypted credit card numbers. -- GT

**Comment by trinitywebmedia** [comment]
@keberletwm Let's talk more about this and engage Steve. Ticket closed.

**Comment by keberletwm** [comment]
Norwescap.org is down as of 8:32 AM 8/9/2021 due to issues surrounding previous hack and vulnerabilities.

**Comment by trinitywebmedia** [comment]
Thank you for letting me know @keberletwm. 

Right now, there are two other sites I am either cleaning or getting removed from a blacklist. I will look at this as soon as I can. -- GT

**Comment by trinitywebmedia** [comment]
I cleaned the site (again.) The site is up and running. Surprised no one from Norwescap responded to any messages here, via text or email. -- GT
