### ISSUE TITLE
Updates

### ISSUE THREAD

**Issue by KasiaWM** [trinitywebmedia/Norwescap-Tickets#29]
Board Page:
Please remove Michael Busche from the Sussex County section and replace with Jesse Oliver.  Also, under the “Officers” caption please remove Thomas Pepe, Chair and replace with James Buehler, Chair and add Christine Nesbitt, Vice Chair / Secretary.

**Comment by trinitywebmedia** [comment]
Once a contract is executed and the server is restored safely will schedule updates. -- GT

**Comment by trinitywebmedia** [comment]
Timeline Update - to be completed by 8/19 -- GT

**Comment by trinitywebmedia** [comment]
COMPLETED
