### ISSUE TITLE
NorwesFest Pop Up

### ISSUE THREAD

**Issue by keberletwm** [trinitywebmedia/Norwescap-Tickets#3]
Are you able to add this image to our website as a pop-up to notify viewers of our upcoming event? 

The main purpose is to notify participants when tickets go on sale and drive viewers to the Norwesfest landing page once it fully created. 

You can use this verbiage for now for the pop-up window along with the attached image. 

"Join us for Norwescap’s first Northwest Fest on June 26th! Northwest fest is an all-day event! Get notified when tickets go on sale. More details coming soon!" Let me know if you have any questions . 

[NorwesFest Save the Date Invitation.pdf](https://github.com/trinitywebmedia/Norwescap-Tickets/files/6286692/NorwesFest.Save.the.Date.Invitation.pdf)

**Comment by trinitywebmedia** [comment]
Does this push out to any pages or is it a simple popup? If it's just for information, this may be more intrusive than good. Please let me know and I will proceed accordingly. GT

**Comment by trinitywebmedia** [comment]
11:45 am - 12:30 pm (45 min)

Popup is done as requested.
