### ISSUE TITLE
CFRS Update to forms

### ISSUE THREAD

**Issue by KasiaWM** [trinitywebmedia/Norwescap-Tickets#30]
[NJCK  Application Spanish 4-30-2021 (1).pdf](https://github.com/trinitywebmedia/Norwescap-Tickets/files/6969498/NJCK.Application.Spanish.4-30-2021.1.pdf)
[Subsidy Application Packet BW 4-29-21 (2).pdf](https://github.com/trinitywebmedia/Norwescap-Tickets/files/6969500/Subsidy.Application.Packet.BW.4-29-21.2.pdf)

              Would you please update the CFRS page by replacing the current applications for the NJCK subsidy assistance program with the ones attached

https://norwescap.org/education/child-and-family-resource-services/
middle of page says english and spanish

**Comment by trinitywebmedia** [comment]
Can you please provide the urls of the appropriate pages.

Once a contract is executed and the server is restored safely will schedule updates. -- GT

**Comment by KasiaWM** [comment]
Greg. I'm confused. The contract was executed yesterday. 
Did you not know?
They need a timeframe as to what that means.... please provide a timeframe we can share.

**Comment by keberletwm** [comment]
Kasia,

The executed contract will begin effective Monday. We will be working on restoring the server this week and removing the malware still impacting the site. These updates will be completed by end of day Wednesday 8/18/2021.

**Comment by trinitywebmedia** [comment]
8/18/21 works on my end as long as the server cleanup and transfer goes smoothly with no further infection. Please advise Norwescap parties -- GT

**Comment by trinitywebmedia** [comment]
Regardless, page urls are still needed to fulfill request. -- GT

**Comment by KasiaWM** [comment]
Notified Mark and Maritza.

**Comment by trinitywebmedia** [comment]
Can we add Mark and Maritza to these tickets for full visibility to scheduling, request details etc -- GT

**Comment by trinitywebmedia** [comment]
Timeline Update - to be completed by 8/19 -- GT

**Comment by trinitywebmedia** [comment]
Q: There are three applications. Do these replace all three county forms? Or are they added in addition to these forms. Please advise. - GT
<img width="791" alt="Screen Shot 2021-08-18 at 12 37 53 PM" src="https://user-images.githubusercontent.com/31321275/129937690-fae90888-e78d-4858-a45f-492d818ab4bf.png">

**Comment by KasiaWM** [comment]
updae all in all counties.

**Comment by trinitywebmedia** [comment]
Done. -- GT
