### ISSUE TITLE
CFRS required by state

### ISSUE THREAD

**Issue by KasiaWM** [trinitywebmedia/Norwescap-Tickets#31]
Add to CFRS Page Please 

http://norwescap.org/education/child-and-family-resource-services/
[FINALIZED MRS Language for CCR&R websites.docx](https://github.com/trinitywebmedia/Norwescap-Tickets/files/6988517/FINALIZED.MRS.Language.for.CCR.R.websites.docx)

**Comment by trinitywebmedia** [comment]
Timeline Update - to be completed by 8/19 -- GT

**Comment by trinitywebmedia** [comment]
This was added to the bottom of the page.
