### ISSUE TITLE
REPLACE HOME PAGE NORWESFEST- SHORT WINDOW

### ISSUE THREAD

**Issue by KasiaWM** [trinitywebmedia/Norwescap-Tickets#33]
short window to vote. need up ASAP on homepage.

INFO: 

We are thrilled to be a finalist for State Farm’s Neighborhood Assist program to win a $25,000 grant, that will support our Compadres program, which brings kids together in safe, nurturing environment to have fun while furthering their learning, exploring careers, building life skills, and boosting confidence. Norwescap is asking community members to help them win the grant by casting votes, up to ten times per day, by visiting https://bit.ly/VoteNorwescap.  
We can't win without you!  The voting period runs today through August 27 so VOTE NORWESCAP TODAY!  

Thank you for your support!!

IMAGE LINK  https://bit.ly/VoteNorwescap

![239211922_4621302407903670_4445489280806256893_n](https://user-images.githubusercontent.com/83297632/130278897-66e6e96f-8f4f-4ef8-bbc6-518105e3b8be.png)

**Comment by trinitywebmedia** [comment]
I will have this up by Tuesday 8/21 eod. -- GT

**Comment by KasiaWM** [comment]
Hey Greg,
Given the short window to Vote Mark was asking if we can get it up by this weekend. Any chance?

**Comment by trinitywebmedia** [comment]
No. I am out of the office until Monday, and I have a couple of urgent items to take care of before I get to this one. -- GT

**Comment by trinitywebmedia** [comment]
This is done. In the future, if there is anything that is urgent -- that you know is coming up...please let us know ahead of time, so I can earmark dev time for the request. -- GT

**Comment by KasiaWM** [comment]
Thanks. I always try to let you know anything thats coming up. This grant is completely out of the blue as much for you as for me. Sorry for dropping this on you guys, I hate doing that. 
KW

**Comment by trinitywebmedia** [comment]
Here's the deal. Kevin and I do not want to be the reason anything fails. We are aware that emails about the grant went out on Thursday. Had we known then, I could of had this on the site through the weekend. 

We just need a heads up.

<img width="426" alt="Screen Shot 2021-08-23 at 10 22 13 AM" src="https://user-images.githubusercontent.com/31321275/130467188-5ec0119d-0c5e-4657-b3a8-06da74d09ca0.png">

**Comment by KasiaWM** [comment]
Sure, I can see how you assume that this was something that we had lead time on.  The initial conversation, last Tuesday, when we had a call about the requirements to promote this grant, revolved around doing a pop up. Which I strongly discouraged because of dev hours and the very short lived window to move people. My recommendation was to do emails, both personal and via mail campaign and share on all social media sites per the Grant's Officer.  Just didn't make sense to invest the time for a pop up or really the website when this is more of a popularity contest and trends better elsewhere.  Anyway, it doesn't matter because here we are.

**Comment by trinitywebmedia** [comment]
Regardless....now that we know this grant voting has a short window and an expiration date, please let us know what you want to replace the 'VOTE NORWESCAP' area on the site once the voting is complete.

**Comment by KasiaWM** [comment]
Just got a note from Heather. Website says Vote NorwesFest, instead of Vote Norwescap. Can you please change. 

I'll ask what they would like it replaced with.

**Comment by trinitywebmedia** [comment]
Negative.
