### ISSUE TITLE
Job Postings

### ISSUE THREAD

**Issue by nwcoperations** [trinitywebmedia/Norwescap-Tickets#34]
I am having problems with the area pertaining to the Hours per week for the positions and also the weeks per year. Someone had brought to my attention that these 2 field on the job posting site do not come up on our website..  I enter all the info in & then this is the problem.
I am not sure how long this has been an issue, but i am reaching out to see if someone can help.
Thank you,

Peggy Curtis
Norwescap
908-454-7000 ext: 1113

**Comment by trinitywebmedia** [comment]
Thank you for the note. I will review this today, and let you know what I find and the fix. - GT

**Comment by trinitywebmedia** [comment]
Peggy -- I looked at this form and made sure the proper merge tags were inserted in the form and post creation. It looks like everything is there. I also made these fields required to force their posting. If the information is not available at time of posting just use n/a to satisfy the required fields. 

Let me know if you have any other issues. -- GT
