### ISSUE TITLE
Job Postings

### ISSUE THREAD

**Issue by nwcoperations** [trinitywebmedia/Norwescap-Tickets#35]
My apologies for bringing up this issue again, However, i can see the info that is needed on the (contact us) new submission page, but i just posted another job & it is still not showing up our norwescap website. If i am doing something wrong, please let me know.

Thank you,
Peggy

**Comment by trinitywebmedia** [comment]
Quick question: You are using https://norwescap.org/job-posting-system/ to fill out the form -- correct?

**Comment by nwcoperations** [comment]
Yes I am.

**Comment by trinitywebmedia** [comment]
Ok, Thank you for clarifying. (I just needed to make sure, so we are looking at the same things.)

**Comment by trinitywebmedia** [comment]
Added from 9/7 ticket to condense:

I need the website job posting to read "Hours per week for the postion- tab, along with the "Weeks per year for the position"- tab. I also do not see the "Email Address"- tab.

We are looking into these matters, as today is the first day back in the office from before Labor Day.

**Comment by trinitywebmedia** [comment]
Please leave all correspondence regarding this matter within this ticket and not a new one. Thank you. -- GT

**Comment by trinitywebmedia** [comment]
<img width="1440" alt="Screen Shot 2021-09-08 at 12 07 07 PM" src="https://user-images.githubusercontent.com/31321275/132545142-dd5b30eb-4c6e-42ed-936b-192e25c317b8.png">

I re-created the form, tested it, and placed it on the Job Posting System. As per the screenshot, you will see that the fields missing previously now work.

Please note: The form may look a little different, but I followed the basic outline from what we had previously.

I will now mark this issue closed.

**Comment by nwcoperations** [comment]
Good Morning,

I would like to say thank you for taking the time to work these issues out. However, as most of the things have been fixed  some have caused others to change.
The last thing I need is to have a “Send application/resume and/or letter to:” line just above the email address line.

Thank you in advance for all your hard work on all these things,
Peggy Curtis

**Comment by trinitywebmedia** [comment]
Thank you for pointing this out Peggy. I added the necessary line to the source code of the post. -- GT

//*FOR FUTURE REFERENCE*//

<strong>Date: </strong>{Date:2}
<strong>Job Title: </strong>{Job Title:1}
<strong>Summary:</strong> {Job Summary:3}
<br>
<hr>
<br>
<strong>Send application/resume and/or letter to:</strong>
<strong>Email:</strong>  {Email:8}
<strong>Phone: </strong>{Telephone Number:10} / <strong>Fax: </strong>{Fax Number:9}
<hr>
<strong>Norwescap Program:</strong> {Norwescap Program:13}
<strong>Job Location:</strong> {Job Location:14}
<strong>Job Description:</strong><br>
{Job Description:15}
<br>
<strong>Number of Positions To Fill:<s/trong> {Number of Positions To Fill For Title and Location:4}
<strong>Number of Weeks Per Year:</strong> {Number of Weeks Per Year For Posted Position:5}
<strong>Number of Hours Per Week: </strong>{Number of Hours Per Week For Posted Position:6}
<strong>Rate of Pay: </strong>{Rate of Pay:11}
<hr>
<strong>Required Level of Education: </strong>{Required Level of Education:17}
<strong>Required Number of Months / Years Experience:</strong> {Required Number of Months / Years Experience:18}
<strong>Required Degree of Formal Training: </strong>{Required Degree or Formal Training:19}
<strong>Required License Certificate or Registration: </strong>{Required License Certificate or Registration:20}
<br>
<strong>Deadline For Submission: </strong>{Deadline For Submission:21}
<br>
<br>
<a class="button" href="https://norwescap.org/employment-application/">Apply For Position</a> <a class="button" href="https://norwescap.org/wp-content/uploads/2019/07/Employment-Application-6-11-2019.pdf">Download Application</a>

**Comment by nwcoperations** [comment]
The information I spoke to you about this morning…. The” Send Application/resume and/or letter to:” only transferred  to the 1 job posting, not the job posting system.  I have to manually put all that info in again.
I am sorry this has been such a difficult process.

Thanks again,
Peggy

**Comment by trinitywebmedia** [comment]
Ok. I will investigate this further.

**Comment by trinitywebmedia** [comment]
![Bilingual_Family_Worker_-_Norwescap](https://user-images.githubusercontent.com/31321275/132755243-c4905227-9e38-48b4-9869-36bbec89c095.jpg)

Is this not what you needed? Please let me know if I misunderstood.

**Comment by nwcoperations** [comment]
There is nothing in your email. Can you resend it.

**Comment by trinitywebmedia** [comment]
While you can use the ticketing system via email, I posted the screenshot at Git Hub [](https://github.com/trinitywebmedia/Norwescap-Tickets/issues/35) for ease of keeping things together. It makes things easier. Please review there and comment accordingly.

**Comment by nwcoperations** [comment]
Good Morning,

This whole thing has to be as frustration to you as it is to me? I am not sure if we could talk on the phone so I can better tell you the needs of posting these jobs, it just seems like we are going in circles here.
If we are able to have a call please let me know & I will be at my desk all day.

Thank you,
Peggy

908-454-7000
Ext. 1113

**Comment by trinitywebmedia** [comment]
Additional form field added for Send Application/Resume and/or Letter to:

This should close this issue out. Please let me know if there is anything else needed for this system. Thx -- GT

**Comment by nwcoperations** [comment]
Hi, It’s just me again. All of the pertinent information is on the posting now, but, the problem now is that the” Number of positions to fill:” thru “Deadline for Submission” all have a black line through them.

Thanks.
Peggy

**Comment by trinitywebmedia** [comment]
That's strange, I have never seen this issue. When I get back to the office I will look at it. -- GT

**Comment by trinitywebmedia** [comment]
Bad line of code fixed. Fingers crossed, we should be good to go. -- GT

**Comment by nwcoperations** [comment]
Hi, 
Its Peggy again, i have received quite a few emails from employees telling me that there is a Test Position on the 2nd page of the job posting site. I looked & it is there & its on latin. I guess its been there since Sept 9th.  Can you take care of this please.
Thank you,
Peggy

**Comment by trinitywebmedia** [comment]
Fixed. Thank you -- GT

Greg Taylor

Co-Founder & Lead Developer

m. (856) 473-0690

Trinitywebmedia.com <http://trinitywebmedia.com> | We Solve Business
Problems

Stockton, NJ | Philadelphia, PA

<http://facebook.com/trinitywebmedia> <http://twitter.com/trinitywebmedia>
<http://instragram.com/trinitywebmedia> <http://trinitywebmedia.com>

Listen to Our Podcast: The New Marketing Show
<http://trinitywebmedia.com/marketing-podcast/>
