### ISSUE TITLE
Replace vote 

### ISSUE THREAD

**Issue by KasiaWM** [trinitywebmedia/Norwescap-Tickets#36]
Replace vote 

As we ease back into a post-covid world, please help us in recognizing Hunger Action Month on September 14, 2021... 
Stop by Norwescap's Food Bank from 4-6pm and pick up a warm bowl of soup. Call to reserve your meals to go! 908 454 4322
![236664374_4277625925660672_7501941335410201205_n](https://user-images.githubusercontent.com/83297632/131861822-ad871d1f-3b5e-4efe-813b-eeb2f6416f68.jpg)

**Comment by trinitywebmedia** [comment]
Thank you. I am out of town starting today and will have this up by Tuesday morning -- GT

**Comment by KasiaWM** [comment]
Hey Greg,
Can you update this please?

**Comment by trinitywebmedia** [comment]
This will be done today when I am back in the office. -- GT

**Comment by trinitywebmedia** [comment]
DONE. FYI: Home page images are best horizontal with a max width at 1000px - GT
