### ISSUE TITLE
Update Address

### ISSUE THREAD

**Issue by KasiaWM** [trinitywebmedia/Norwescap-Tickets#37]
Hunterdon County
Norwescap Early Head Start
116 Main Street
Flemington, NJ 08822
908-284-4757
fax: 908-237-4533

https://norwescap.org/education/head-start/

Remove Ringos

**Comment by trinitywebmedia** [comment]
Thank you. I will have this taken care today. -- GT

**Comment by trinitywebmedia** [comment]
DONE
