### ISSUE TITLE
Website Issues

### ISSUE THREAD

**Issue by nwcoperations** [trinitywebmedia/Norwescap-Tickets#38]
This is the 3rd ticket i have summited &  i am still having the same issues. I need the website job posting to read  "Hours per week for the postion- tab,  along with the "Weeks per year for the position"- tab. I also do not see the "Email Address"- tab.  Can this please be addressed today! 
 Thank you,
Peggy

**Comment by trinitywebmedia** [comment]
Hi Peggy. Today is our first day back from vacation and we are handling tickets as the come in. I am deleting this ticket and adding the new issue to the other, still open ticket from pre-Labor Day.

This is a complicated issue and we are looking at it. Please be patient. -- GT
