### ISSUE TITLE
Events Tab

### ISSUE THREAD

**Issue by KasiaWM** [trinitywebmedia/Norwescap-Tickets#39]
Kevin, & Greg, 
We would lke to change the way the events page presents. We would like to switch it to a simple page, no calendar listing or dates... Please see the attached doc. 
[2021 Fall Special Events.docx](https://github.com/trinitywebmedia/Norwescap-Tickets/files/7147841/2021.Fall.Special.Events.docx)

**Comment by trinitywebmedia** [comment]
Thank you. We will look at this and follow up with any questions. This should be done by eod 9/14 -- GT

**Comment by trinitywebmedia** [comment]
New page created and linked to main nav. Also, I removed the upcoming events section on the homepage since it was empty and calendar driven. -- GT
