### ISSUE TITLE
Homepage

### ISSUE THREAD

**Issue by KasiaWM** [trinitywebmedia/Norwescap-Tickets#40]
would like to replace the space for the empty bowls/ voting we had that links to the landing page for events....upcoming events  Can you please tell me what size image?

**Comment by trinitywebmedia** [comment]
I would design something that is about 1000w x 400 px 

Once I add to the site, we can link the image to: https://norwescap.org/upcoming-events/

**Comment by KasiaWM** [comment]
![Norwescap Banner Calendar](https://user-images.githubusercontent.com/83297632/133488742-853f7766-d9ee-490d-89f1-f486e180d738.png)

Hey guys can you update with this on the homepage and link.... also the formatting is super weird. can we adjust the spacing it is a bit confusing with so much space between each.

**Comment by trinitywebmedia** [comment]
I will have this done by week's end.

The spacing is due to having us remove a whole area the site was developed around. (Events w/ a background hero image.) Sometimes, this is what happens when you try to retrofit pieces to a design ad hoc.  I will see what can be done.

**Comment by trinitywebmedia** [comment]
DONE
