### ISSUE TITLE
Rolling Calendar Updates 

### ISSUE THREAD

**Issue by KasiaWM** [trinitywebmedia/Norwescap-Tickets#41]
Remove--- Empty Bowls on events page, and next Monday can you please remove the 9/18 and 9/19 events.

**Comment by trinitywebmedia** [comment]
Ok, this really does not make sense. Why did we get away from using a traditional calendar that can be managed as events come up, and get removed as dates pass? To me, it's just a matter of managing the calendar.

Either way, I can have this done by eod Friday. -- GT

**Comment by KasiaWM** [comment]
Don't worry about that tid bit right now. They will be addressed in the redesign. :-)

**Comment by trinitywebmedia** [comment]
DONE - GT
