### ISSUE TITLE
Board Section Change Request

### ISSUE THREAD

**Issue by baakmanm** [trinitywebmedia/Norwescap-Tickets#42]
https://norwescap.org/board-of-trustees/

Please change the appearance of the name of AntoineGayles under the Morris County to Antoine Gayles 

Thanks!

**Comment by trinitywebmedia** [comment]
Fixed. Please note: when it comes to posting content, we copy and paste what we receive. Please make sure all copy is edited and proofed before sent. Thanks! -- GT
