### ISSUE TITLE
Blog Posts & Images

### ISSUE THREAD

**Issue by KasiaWM** [trinitywebmedia/Norwescap-Tickets#43]
Please see images & blog posts.

![Shoprite](https://user-images.githubusercontent.com/83297632/135623095-cf552111-21e6-488e-a992-828630a5ecff.jpg)

![Hunger Action Month](https://user-images.githubusercontent.com/83297632/135623102-7800d157-f775-45c4-9a46-1f688f0d8932.jpg)
[Hunger Action Month.docx](https://github.com/trinitywebmedia/Norwescap-Tickets/files/7267241/Hunger.Action.Month.docx)
[ShopRite Race for Hunger.docx](https://github.com/trinitywebmedia/Norwescap-Tickets/files/7267243/ShopRite.Race.for.Hunger.docx)

**Comment by trinitywebmedia** [comment]
Thanks. Got it. We will have this on- site by Tuesday 9:00 am. -- GT

**Comment by trinitywebmedia** [comment]
DONE -- GT
