### ISSUE TITLE
CFRS Website Changes

### ISSUE THREAD

**Issue by cfrsnorwescap** [trinitywebmedia/Norwescap-Tickets#44]
[http://norwescap.org/education/](url)

Under Early Childhood Education, first paragraph, first sentence - please change "Child and Family Resources" to "Child and Family Resource Services"

Under Early Childhood Education, first paragraph, fourth sentence - please change "Child and Family Resources" to "Child and Family Resource Services"

Under Early Childhood Education, second paragraph, second sentence - please change "Child and Family Resources" to "Child and Family Resource Services"

**Comment by trinitywebmedia** [comment]
DONE
