### ISSUE TITLE
Addition/deletion from "New Donation" email notification

### ISSUE THREAD

**Issue by hlthomps** [trinitywebmedia/Norwescap-Tickets#47]
Please remove the following individuals from the email notifications regarding new donations via the website:
Eileen Nelson (nelsone@norwescap.org)
Kasia McManamon (mcmanamonk@norwescap.org)

Please add the following person to this email notification list:
Michele Kennedy, kennedym@norwescap.org

Thank you!

**Comment by trinitywebmedia** [comment]
I will look at this now.

**Comment by trinitywebmedia** [comment]
We just made these changes for you. -- GT
