### ISSUE TITLE
Re-activate URL norwescap.org/give-thanks

### ISSUE THREAD

**Issue by hlthomps** [trinitywebmedia/Norwescap-Tickets#48]
Hello,

As we are working on getting our Food Bank Thanksgiving appeal ready to print, we would like to have a dedicated landing page for online donations as we have done with other recent appeals. I will send the content for the page within the next couple of days, but I wanted to confirm that we can use the URL **www.norwescap.org/give-thanks** as the page. I'm told we used it in the past but it doesn't appear to be currently active. The intention is for the page to have an introductory paragraph of text, an image, and a donation form.

Please let me know if we can use this URL so we can move foward with the printing of the appeal. Thank you!
Heather

**Comment by trinitywebmedia** [comment]
Heather -- thank you for the heads up. The url /give-thanks has never been used before on the site, so you are free to use it for the campaign. 

I will leave this ticket open. Please upload all content and assets here when ready,

Take care -- GT

**Comment by trinitywebmedia** [comment]
Also as a head's up...you will want to make sure you have access to the Norwescap STRIPE account.

**Comment by hlthomps** [comment]
Thanks! I do already have access to Stripe so I'm in good shape there. I will upload content for this page as soon as I can finalize it. Thanks!

**Comment by hlthomps** [comment]
[2021 Oct Fall Appeal web donation page text.docx](https://github.com/trinitywebmedia/Norwescap-Tickets/files/7398009/2021.Oct.Fall.Appeal.web.donation.page.text.docx)
![Fall Appeal Little Girl Image](https://user-images.githubusercontent.com/83599303/138467890-0d1c1de9-d14d-4061-b09b-005ac3b08d94.jpg)

Good morning - the file for the page text is attached, along with an image we would like included on the page. We need a donation form embedded on the page with the dollar amounts I've indicated on the Word doc. I've also indicated some additional fields I would like included on the donation form if possible. Please let me know if you have any questions or if there are any issues with this. Thanks!

**Comment by trinitywebmedia** [comment]
Thank you Heather. I will review today and schedule dev for early next week. -- GT

**Comment by trinitywebmedia** [comment]
Heather --- please review the page [](https://norwescap.org/thanksgiving-for-all/) and let me know if this is inline with what you want. Once approved, I will change the permalink url to /give-thanks

I suggest we change the page header to something more relevant (image size approx 1200 x 400)
I can also customize the 'Donate Now' and 'Other Donation Amount' text as needed. Please advise -- GT

**Comment by hlthomps** [comment]
Thanks, Greg. What link should I use to review the page?

**Comment by trinitywebmedia** [comment]
I'm sorry, I thought the text linked in the above message. Please review https://norwescap.org/thanksgiving-for-all/ -- Thanks.

**Comment by hlthomps** [comment]
Thanks! I agree re: changing the banner image. I don't have an appropriate in-house image at my fingertips - do you have access to stock photos that you can draw from? I'm thinking just a nice, colorful, Thanksgiving-food-y image would be good.

I'm fine with the button text and the form. Can you just shift the Donate Now button to be above the "Thank you for your generosity" paragraph?

**Comment by trinitywebmedia** [comment]
No problem. I found an image and sized it correctly. Please review once again and I will change url when approved.
https://norwescap.org/thanksgiving-for-all/

SIDE NOTE: All pages were to be supplied to us from communications. This fell by the wayside, so if there are other pages that require more relevant imagery please advise. -- GT

**Comment by hlthomps** [comment]
Great - we are good to publish. Thank you!

Re imagery for the other pages - that did come up on our discussion on Friday with Kevin. We have some more immediate work we want to get done on the site prior to year end, but updating the images on some pages will definitely be part of our future updates. Thank you.

**Comment by trinitywebmedia** [comment]
We are live. The page lives at: https://norwescap.org/give-thanks/

Please note: All donations will be allocated in the Stripe and Give report as Thanksgiving For All.
I will close this ticket, but if this page needs any revisions, please feel free to re-open this ticket and we can go from there. Thank you. -- GT
