### ISSUE TITLE
Address Change

### ISSUE THREAD

**Issue by nwcoperations** [trinitywebmedia/Norwescap-Tickets#49]
Our IT person Steve said he had asked Kasia to put in a tickets asking her to change an address for Flemington EHS & it was never  done. Here is the corrected info for this new ticket. Early Head Start
                                                                              Flemington Center
                                                                             116 Main Street
                                                                              Flemimgton, NJ 08822
                                                                              908-824-2525
                                                                              Fax:908-824-2553                 Thank You, Peggy

**Comment by trinitywebmedia** [comment]
Thank you for your note Peggy. I have a feeling this is something we will hear more and more of....
Your change was completed. Please note: we typically copy and paste all information sent. This instance I was able to catch a typo, but it may not always be the case.

Please tell Steve this is completed. -- GT
