### ISSUE TITLE
NorwesFest Form/ Ticket Sales

### ISSUE THREAD

**Issue by KasiaWM** [trinitywebmedia/Norwescap-Tickets#5]
[Norwescap 6-26-2021 nightime.docx](https://github.com/trinitywebmedia/Norwescap-Tickets/files/6415193/Norwescap.6-26-2021.nightime.docx)
[Norwescap 6-26-2021 daytime.docx](https://github.com/trinitywebmedia/Norwescap-Tickets/files/6415195/Norwescap.6-26-2021.daytime.docx)

Menus for the form.  Note: one change…. We will not be having cream cheese on the kids sandwiches for daytime menu. It will be a strawberry jam sandwich. (peanut/ nut free jam only).

We would like this ready to go asap.  Can you please send the proposal and timeline for getting this up?

**Comment by trinitywebmedia** [comment]
Kevin will call to discuss the proposal. I am not sure this is something we should do since all other forms are very different and off the Norwescap site. Kevin, Please advise. -- GT

**Comment by KasiaWM** [comment]
Yes. Kevin and I met last week and discussed this specific form.  It's def outside of dev hours and requires a separate proposal.  We discussed a layout and plan of how the form would function.  After showing the team internally now DP forms are a PITA, I will not even entertain using them for something like this. 

We also discussed a plan on how to use dev hours moving forward and how to prioritze the asks.  I'm currently pitching a landing page redesign as Kev suggested, instead of putting a bandaid on it.  I think everyone here is going to be on the same page.

**Comment by trinitywebmedia** [comment]
Kevin -- please review the above - GT

**Comment by keberletwm** [comment]
Kasia,

Just to recap all aspects of Norwesfest:
Location: Ort Farms

• Date: 6/26/2021
Sessions: 2
Day: Children/Family Oriented
Evening: Adult Oriented

Food Options: 
Day: 
[Norwescap.6-26-2021.daytime.docx](https://github.com/trinitywebmedia/Norwescap-Tickets/files/6415957/Norwescap.6-26-2021.daytime.docx)
Evening: 
[Norwescap.6-26-2021.nightime.docx](https://github.com/trinitywebmedia/Norwescap-Tickets/files/6415959/Norwescap.6-26-2021.nightime.docx)

Form Should Include:
• Number of Tickets and attendees names
• Which session they plan on attending
• Their food choices (by paticipant name)

Additional Information requested:
• Will attendees be purchasing the tickets via this form?
• Thank you confirmation page to direct attendees once form has been completed
• Confirmation email verbiage

**Comment by keberletwm** [comment]
Kasia, 
Thank you for your time.
To recap our phone conversation. We need the following info to accurately gauge how many dev hours this request will take:

• Ticket prices for each option (Day Session- Adult/Child Pricing, Evening Session: Adult Pricing **[Received 5/4/21]**
• Thank you page verbiage
• Signup email verbiage
• Stripe login information 
• Ticket receipt verbiage - GT
• Are we generating a guest list for event check-in or a printable ticket to redeem? - GT
• One ticket per party or one ticket per attendee? - GT

**Comment by trinitywebmedia** [comment]
To clarify, we are building a basic eComm solution for event attendance -- GT

**Comment by keberletwm** [comment]
Received from Heather Thompson 9:24 AM 5/4/2021:

**Family Fun Day: 11am-3pm**
All tickets include farm admission and activities, individually-boxed picnic lunches, wine/beer tastings, and soft drinks
Adult: $65
Child (12 and under): $25
Family Fun Package:  $750 – includes event tickets for 8 adults + up to 12 children, plus 4 Norwescap picnic blankets (value $850)

**Sunset Social Affair: 5:30-9pm** Adult Only 21+ 
All tickets include farm admission and activities, individually-boxed gourmet picnic dinners, and wine, beer and cocktails
Adults: $150
Sunset Package: $1,000 – includes event tickets for 8 adults, plus 4 Norwescap picnic blankets (value $1230)


NorwesFest All Event Ticket (adults only 21+): $175

**Comment by KasiaWM** [comment]
For Sunsset Social Affair please indicate (Adult Only 21+)

**Comment by trinitywebmedia** [comment]
Kevin -- let's shoot for a proposal by week's end once all info is received -- GT

**Comment by trinitywebmedia** [comment]
Questions:

• Are we generating a guest list for event check-in or a printable ticket to redeem? - GT
• One ticket per party or one ticket per attendee? - GT
• Are we re-designing the Event Landing Page? -KE

**Comment by keberletwm** [comment]
As per this afternoons Call with Kasia and Heather:

• Are we generating a guest list for event check-in or a printable ticket to redeem? - Guestlist organized in parties by purchase
• One ticket per party or one ticket per attendee? - Email confirmation and guestlist will serve as tickets. No action required
• Are we re-designing the Event Landing Page? - No

We also discussed an additional Form that would accommodate tickets accompanying sponsorship. This form would include:
• Sponsor Name
• Daytime or evening event
• Number of Guests
• Guest name and food selection for each attendee

**Comment by keberletwm** [comment]
Project Correspondence 5/7/21 4:05 PM **NOTE: Email Receipt Attached**
[Ticket Confirmation Email.docx](https://github.com/trinitywebmedia/Norwescap-Tickets/files/6444070/Ticket.Confirmation.Email.docx)
_KE- Italics_
**HT- Bold**
####
_Hey Heather,

Thank you for getting this over. 
To answer your questions:_

 **I’m assuming we can have our logo/some sort of branding built into the template?**
_Yes- Norwescaps logo will be included in the confirmation email- would you like anything else to be included?_ **Kasia, do you want to weigh in here? Should we use the Norwescap logo or the NorwesFest logo? Maybe NorwesFest logo at the top, and at the bottom small Norwescap logo with our phone # and website? Kevin, is that doable?**

**Can you walk us through how ticket purchase information will come through to us on the back end?**
_At the time of purchase whoever is designated will receive full order details similar to purchasers confirmation notice._ **Great. Let’s include all three of us on the confirmations – myself, Kasia and Eileen (nelsone@norwescap.org).**

**Are payments going to be processed via Stripe, and if so, will there be information to ensure we can distinguish ticket purchases from regular donations on the Stripe report?** 
_Yes, payments will be processed via Stripe. I will double check with the team how these specific payments will be distinguishable from donations._ **Great, thanks**

**Is it possible to also have our team bcc’d on the email confirmations that go to ticket buyers, so we can see all the details?**
_Absolutely, feel free to provide us with whoever you would like to receive purchase confirmations._ **See above**

_Kasia, I sent over a recap and pricing for us to complete this work. Are we good to move forward. As mentioned yesterday, for us to begin working on this Monday we need approval and the above from Heather to begin. We estimate this being completed in 3-4 business days once we receive confirmation to begin._

**Comment by keberletwm** [comment]
Client Email 5/7/21 4:10 PM - Heather Thompson

Follow up once approved:
Kevin, something else that popped into my head – I’d like to make sure we have an option on the ticket form for “I cannot attend but would like to make a donation of $xxx (blank) to support Norwescap.” I’ve always found that we can actually raise a decent amount of money from people who are on our mailing list and can’t or don’t want to come but they’ll donate $20 or $50 (or sometimes a lot more!).

So maybe when we add the ticket purchase link to the event homepage we need to label it something like “Purchase Tickets/Make a Donation” so people know they can do either.

**Comment by keberletwm** [comment]
Additional Content Received:

• NorwesFest Logo
• Receipt Verbiage
![NorwesFestGathering](https://user-images.githubusercontent.com/57730919/117860523-62408e80-b25e-11eb-988d-a5e5463f2231.png)
[Ticket Confirmation Email 1.docx](https://github.com/trinitywebmedia/Norwescap-Tickets/files/6461001/Ticket.Confirmation.Email.1.docx)

**Comment by trinitywebmedia** [comment]
@keberletwm I have a couple of questions for you. Let's connect when possible. -- GT

**Comment by keberletwm** [comment]
Approved Scope of Work: 

• RSVP Form:  AM/PM/All Day Tickets and Food Selection 
• Payment gateway for Event
• Email receipt for Ticket Purchases
• Two (2) Data exports of guest list & info in spreadsheet form

**Comment by trinitywebmedia** [comment]
I do not have pricing for the All Day Options. Please send ASAP -- GT

**Comment by trinitywebmedia** [comment]
Please send all updates to Github ticketing. We want all project correspondence in one place.

[All day info added to proper line in tickets.] 

NOTE: We are creating a form to purchase tickets and capture event attendee information. There is no room for additional event verbiage. All event information other than specific attendee data should be on page. -- GT

**Comment by KasiaWM** [comment]
NorwesFest All Event Ticket (adults only +21): $175
Enjoy the best of NorwesFest by attending with your family during the day, then come back for grown-ups’ night out! Includes (1) adult admission to Family Fun Day + (1) adult ticket to Sunset Social Affair.  Please note that NorwesFest will close between 3 – 5:30pm to allow for setup between events.

**Comment by trinitywebmedia** [comment]
This is complete. The subdomain is tickets.norwescap.org 
I also changed links and added buttons to the NorwesFest post. -- GT
