### ISSUE TITLE
URGENT: Add in Provider Letter to Website

### ISSUE THREAD

**Issue by cfrsnorwescap** [trinitywebmedia/Norwescap-Tickets#50]
https://norwescap.org/education/child-and-family-resource-services/ 
Please add in a link to the attached document at the top of the page above "Emergency and Disaster Child Care Policy" and entitle the link "November 2021 Reimbursement and Copay Change Provider Letter"

[DFDI 21-10-01--Attachment 1 November 2021 Reimbursement and Copay Changes Provider Letter.pdf](https://github.com/trinitywebmedia/Norwescap-Tickets/files/7435724/DFDI.21-10-01--Attachment.1.November.2021.Reimbursement.and.Copay.Changes.Provider.Letter.pdf)

**Comment by trinitywebmedia** [comment]
DONE -- GT

Please note: Most requests will take up to 48 hours to fulfill without prior notice. I was in the site and able to accommodate this request immediately.
