### ISSUE TITLE
URGENT: Add in Parent Letter to Website

### ISSUE THREAD

**Issue by cfrsnorwescap** [trinitywebmedia/Norwescap-Tickets#51]
https://norwescap.org/education/child-and-family-resource-services/ 
Please add in a link to the attached document at the top of the page above "Emergency and Disaster Child Care Policy" and entitle the link "November 2021 Reimbursement and Copay Change Parent Letter"

[DFDI 21-10-01--Attachment 2 November 2021 Reimbursement and Copay Changes Parent Letter.pdf](https://github.com/trinitywebmedia/Norwescap-Tickets/files/7435743/DFDI.21-10-01--Attachment.2.November.2021.Reimbursement.and.Copay.Changes.Parent.Letter.pdf)

**Comment by trinitywebmedia** [comment]
DONE - GT

Please note: Most requests will take up to 48 hours to fulfill without prior notice. I was in the site and able to accommodate this request immediately.

**Comment by trinitywebmedia** [comment]
Also, I appreciate the detailed instructions including the page url. That makes things go much faster on our end and avoids any confusion.

**Comment by cfrsnorwescap** [comment]
Thank you very much for your quick action on this!
