### ISSUE TITLE
Minor text updates to 2 pages

### ISSUE THREAD

**Issue by hlthomps** [trinitywebmedia/Norwescap-Tickets#52]
Hello, 

One of our staff members caught two text errors on our website that need to be corrected.

On the page http://norwescap.org/education/, under "Youth and Emerging Adult Education," 4th line: 
Please change current wording "STEM (Science, Technology, Engineering, and Mathematics) opportunities"
To "STEAM (Science, Technology, Engineering, Art, and Mathematics) opportunities"

On the page http://norwescap.org/education/compadres/, 1st paragraph:
Please delete the word "Children" at the end of the paragraph

Thank you,
Heather

**Comment by trinitywebmedia** [comment]
DONE -- GT
