### ISSUE TITLE
Add Jalen Fields to GitHub

### ISSUE THREAD

**Issue by hlthomps** [trinitywebmedia/Norwescap-Tickets#53]
Please add Jalen Fields, fieldsj@norwescap.org as a user on GitHub. Thank you!

**Comment by trinitywebmedia** [comment]
Invitation sent to Jalen. -- GT

**Comment by trinitywebmedia** [comment]
Also, I removed Kasia from GIT. -- GT

**Comment by hlthomps** [comment]
Thank you!
