### ISSUE TITLE
Language for Post-donation screens and tax receipts

### ISSUE THREAD

**Issue by hlthomps** [trinitywebmedia/Norwescap-Tickets#54]
Hello, Can you please send me copies of the language that donors see on-screen after they make a donation through any of our donation forms, and the language that is sent to them in their email receipts? I would like to review and possibly update for each donation form. Thanks!

**Comment by trinitywebmedia** [comment]
I can get this language pulled and emailed to you by Wednesday, as it is a lot of pages and forms to go through. Thx -- GT

**Comment by hlthomps** [comment]
Thank you, Greg. I’m primarily concerned with the language related to the donation forms that are active right now, which I believe are just three (though please correct me if I’m wrong):
The form that pops up from the “Support Us” button
The form on the “Get Involved” page
The /give-thanks form

Thanks!

**Comment by trinitywebmedia** [comment]
Ok -- I can pull these specifically and get them over sooner. Thank you for the clarification. -- GT

**Comment by trinitywebmedia** [comment]
Form information below in separate comments -- GT

**Comment by trinitywebmedia** [comment]
**Main Navigation 'Support Us'
Form Name: You Are A Vital Partner
Form ID: 108
Revenue to Date: $105,583.25**

DONATION RECEIPT LANGUAGE:

###

Dear {name},

Thank you for your generous contribution. We are truly grateful to have friends and supporters like you.

Your support makes it possible for Norwescap to help thousands of families secure food, shelter, heat and other essential daily needs. It also allows us to work with families to help them work toward a brighter future with programs in early childhood education, healthy living, nutrition, and career development. Your generosity goes a long way in making lives better in northwest New Jersey.

Norwescap works hard to maximize your investment in our work. Our administrative costs are only five cents on the dollar, and our evidence-based programs like Head Start provide a return on investment of between seven and nine dollars for every dollar invested.

Again, on behalf of our 15 board members, 265 staff, 1200 volunteers and 30,000 clients, thank you for your support, and we look forward to doing more great work with you in the coming year.

Please remember that all cash gift made are tax deductible after you subtract the value of any goods or services you received for your donation.

If you received nothing in return, it is full tax deductible (ID # 221-777-156)

Sincerely,
Mark Valli
CEO

<strong>Donor:</strong> {fullname}
<strong>Donation:</strong> {donation}
<strong>Donation Date:</strong> {date}
<strong>Amount:</strong> {amount}
<strong>Payment Method:</strong> {payment_method}
<strong>Payment ID:</strong> {payment_id}

{receipt_link}

###

**Comment by trinitywebmedia** [comment]
**GET INVOLVED: 'Support Our Mission'
Form Name: Support Our Mission
Form ID: 97
Revenue to Date: $28,953.66**

DONATION RECEIPT LANGUAGE: ** USES GLOBAL FORM LANGUAGE **

Dear {name},
 
Thank you for spreading holiday cheer with your generous donation, in the of {amount}, to support Norwescap’s work to transform poverty into opportunity. We are truly grateful to have you as a member of our Norwescap community!
 
Your donation allows us to provide life-changing services that help individuals and families work toward a brighter future. This year has been especially challenging for people with low incomes and limited resources. But thanks to you, Norwescap is able to step in and help - both to help them meet immediate needs like food and housing, and also develop long-term strategies for resiliency and success. 
 
On behalf of all those we serve – nearly 30,000 individuals and families throughout New Jersey - thank you and wishing you and your loved ones a happy and healthy holiday. We look forward to brighter days ahead in 2021 for all!

If you wish to download a link to your donation receipt please the below link.
{receipt_link_url}

Thank you!
Norwescap

###

**Comment by trinitywebmedia** [comment]
**/give-thanks: 'DONATE NOW'
Form Name: Thanksgiving For All
Form ID: 4424
Revenue to Date: $0**

DONATION RECEIPT LANGUAGE: ** USES GLOBAL FORM LANGUAGE **

Dear {name},

Thank you for spreading holiday cheer with your generous donation, in the of {amount}, to support Norwescap’s work to transform poverty into opportunity. We are truly grateful to have you as a member of our Norwescap community!

Your donation allows us to provide life-changing services that help individuals and families work toward a brighter future. This year has been especially challenging for people with low incomes and limited resources. But thanks to you, Norwescap is able to step in and help - both to help them meet immediate needs like food and housing, and also develop long-term strategies for resiliency and success.

On behalf of all those we serve – nearly 30,000 individuals and families throughout New Jersey - thank you and wishing you and your loved ones a happy and healthy holiday. We look forward to brighter days ahead in 2021 for all!

If you wish to download a link to your donation receipt please the below link.
{receipt_link_url}

Thank you!
Norwescap

**Comment by hlthomps** [comment]
Please update the receipt language for /give-thanks to the language in the attached document. Additional updates for other forms to follow. Thank you! 
[2021 Nov Thanksgiving For All Receipt Language.docx](https://github.com/trinitywebmedia/Norwescap-Tickets/files/7548995/2021.Nov.Thanksgiving.For.All.Receipt.Language.docx)

**Comment by hlthomps** [comment]
Please update the receipt language for Support our Mission AND for You are a Vital Partner forms to the language in the attached document. Thank you!
[2021 Nov Support our Mission AND Vital Partner Receipt Language.docx](https://github.com/trinitywebmedia/Norwescap-Tickets/files/7549073/2021.Nov.Support.our.Mission.AND.Vital.Partner.Receipt.Language.docx)

**Comment by trinitywebmedia** [comment]
DONE -- GT
