### ISSUE TITLE
Update to Homepage

### ISSUE THREAD

**Issue by hlthomps** [trinitywebmedia/Norwescap-Tickets#56]
Please replace the Upcoming Events graphic that is currently on the homepage with the attached graphic.
Please have this new graphic link to this site IN A NEW BROWSER TAB: https://one.bidpal.net/vbr2021/welcome
![2021 Norwescap Raffle Banner for Web - Final](https://user-images.githubusercontent.com/83599303/141820834-cb65e410-3447-4062-8491-a731dfaa3e89.png)

**Comment by trinitywebmedia** [comment]
DONE - GT

**Comment by hlthomps** [comment]
Thanks for responding so quickly! Are you able to get the link to open in a new tab, since it’s an external site?

**Comment by trinitywebmedia** [comment]
I just added that for you. Typically, it is not something we like to do and against best practices, because it breaks the UX that even the most elementary Internet user understands. -- GT

**Comment by hlthomps** [comment]
I see. What I had been taught in the past was that an external link should open in a separate tab, but if you recommend strongly against that, I defer to you as the experts.
