### ISSUE TITLE
New Blog post

### ISSUE THREAD

**Issue by hlthomps** [trinitywebmedia/Norwescap-Tickets#58]
Hello,

Please create a new blog post with the text in the attached Word document. **Please note that the highlighted link in the final paragraph needs to link to the attached pdf named "2021 NRTC Norwescap Project Description." The link should not actually be highlighted in the blog post itself.**

Photos to include in blog post are also attached. Please reach out if there are any questions. Thank you!

Heather
[2021 Nov NRTC Program.docx](https://github.com/trinitywebme
[2021 NRTC Norwescap Project Description.pdf](https://github.com/trinitywebmedia/Norwescap-Tickets/files/7565305/2021.NRTC.Norwescap.Project.Description.pdf)
dia/Norwescap-Tickets/files/7565302/2021.Nov.NRTC.Program.docx)

![NRTC Blog Post Pic #2](https://user-images.githubusercontent.com/83599303/142478059-51e73da9-2169-47e7-9211-d2ee31ae360e.png)
![NRTC Blog Post Pic #3](https://user-images.githubusercontent.com/83599303/142478062-dd25834d-51c0-401d-b3b1-f8ee1556fb11.png)
![NRTC Blog Post Pic #1](https://user-images.githubusercontent.com/83599303/142478063-7669e84e-b734-41f9-b2f0-7a1a14ae4640.png)

**Comment by hlthomps** [comment]
It looks like the Word document may not have attached correctly, so here it is again
[2021 Nov NRTC Program.docx](https://github.com/trinitywebmedia/Norwescap-Tickets/files/7565314/2021.Nov.NRTC.Program.docx)
.

**Comment by trinitywebmedia** [comment]
DONE -- GT

https://norwescap.org/news-events/neighborhood-revitalization-tax-credit-program/
