### ISSUE TITLE
Take Down Information

### ISSUE THREAD

**Issue by cfrsnorwescap** [trinitywebmedia/Norwescap-Tickets#59]
https://norwescap.org/education/child-and-family-resource-services/ 

Please take out the following information that is located at the bottom of the above linked webpage: 

***ALL LICENSED CHILD CARE CENTERS WILL BE EMAILED A MARKET RATE STUDY***

The New Jersey Department of Human Services, Division of Family Development, Office of Child Care Operations (DHS/DFD/OCCO) is required by Federal law to conduct a Child Care Market Rate Survey for 2021.  

Beginning August 1, 2021 DHS/DFD/OCCO will be emailing a survey to ALL Licensed Child Care Centers throughout the State from the email address DFD-MarketRateStudy@dhs.nj.gov.  Participation in this survey is critical for the State of New Jersey to help inform policy recommendations for setting Provider payment rates for the Child Care Subsidy Program.

**Comment by trinitywebmedia** [comment]
DONE -- GT
