### ISSUE TITLE
NorwesFest Pop UP

### ISSUE THREAD

**Issue by KasiaWM** [trinitywebmedia/Norwescap-Tickets#6]
Link Pop up to landing page

**Comment by trinitywebmedia** [comment]
Please let us know the correct url for your landing page.

**Comment by KasiaWM** [comment]
https://norwescap.org/norwesfest-2021/

**Comment by trinitywebmedia** [comment]
Kevin will add this to the form's proposal to expedite since no dev hours are available until 5/15 -- GT

**Comment by KasiaWM** [comment]
Hey Guys, I really really need that pop up linking to the landing page provided. Can we please link it now? TIA

Also total side bar, but why is the Norwesfest Post not showing up under blog on the home page? Did I do something wrong? 
TIA

**Comment by trinitywebmedia** [comment]
I will update the popup tomorrow by the end of the day. At that time, I will also look and troubleshoot your post. -- GT

**Comment by trinitywebmedia** [comment]
I added the post problem as an issue to keep things separate to track dev time -- GT
[Issue logged at: https://github.com/trinitywebmedia/Norwescap-Tickets/issues/8 ]

**Comment by trinitywebmedia** [comment]
The new url for the landing page is: https://norwescap.org/news-events/norwesfest-2021/ (please refer to https://github.com/trinitywebmedia/Norwescap-Tickets/issues/8 if needed) -- GT

**Comment by trinitywebmedia** [comment]
Completed.
