### ISSUE TITLE
Year-End donation page

### ISSUE THREAD

**Issue by hlthomps** [trinitywebmedia/Norwescap-Tickets#60]
Please create new landing page www.norwescap.org/give2021 using the text and information in the attached Word document. A couple of notes:
- The donation form on the page should mirror the changes that are in process for the "Support Us" donation page, including the optional fields for Title, Spouse/Partner Name, etc.
- The video to be embedded on this page will be uploaded to Norwescap's YouTube channel on November 29. I will follow up as soon as that video is available.

Please let me know if you have any questions. Thank you! 
[2021 Nov YEA web donation page text.docx](https://github.com/trinitywebmedia/Norwescap-Tickets/files/7584982/2021.Nov.YEA.web.donation.page.text.docx)

**Comment by trinitywebmedia** [comment]
Thank you Heather -- I will look at this today. -- GT

**Comment by hlthomps** [comment]
Requesting an adjustment to my original text as I'm looking at the page - can we add a second “Donate Now” button above the line “Watch the video below…”? That way people going to that page who already have the intention of donating (i.e. from our mailed appeal) won’t have to scroll to find the button.

**Comment by hlthomps** [comment]
It also appears that the "help cover my transaction fees" option isn't working properly on any of the donation forms right now. They are all appearing as "0" regardless of what donation amount is selected.

**Comment by trinitywebmedia** [comment]
New form added above video. I will look at fee recovery once all other critical changes are completed.

**Comment by trinitywebmedia** [comment]
Fee recovery fixed as per ticket #63 -- GT
