### ISSUE TITLE
Carrie Ann Story for "Stories of Resiliency" page

### ISSUE THREAD

**Issue by hlthomps** [trinitywebmedia/Norwescap-Tickets#61]
Please use text in attached file to add Carrie Ann story to top of page https://norwescap.org/success-stories/. YouTube link to embed video will follow later today. Thanks!
[2021 Nov Carrie Ann Story.docx](https://github.com/trinitywebmedia/Norwescap-Tickets/files/7618851/2021.Nov.Carrie.Ann.Story.docx)

**Comment by trinitywebmedia** [comment]
Thank you. I will add to my final changes today and push when completed.

**Comment by hlthomps** [comment]
Great, thank you. As soon as I have the video links for the various pages I will pass them along with clear instructions on which video goes where. If any questions come up as you are working through the last round of changes please don’t hesitate to reach out. Thanks.

**Comment by trinitywebmedia** [comment]
SUCCESS STORIES ARCHIVE PAGE RE-DEV


Add Carrie Ann to top (once video is released) 

Reformat to include thumbnail photos and story previews with easy “click to read more,” improve layout


Success Stories 
Joni Lou Story – get rid of “A Story of Resilience” and “Written by: Gillian Baakman
Nitosha story – get rid of “Stories of Resilience” and “Nitosha’s Story”
“Norwescap Celebrates Katherine’s Success” – change to “Katherine”
Ditto with Yvonne’s story
Delete older stories on p2

**Comment by trinitywebmedia** [comment]
Success stories all renamed or rolled back to drafts -- GT

**Comment by trinitywebmedia** [comment]
DONE -- GT

https://norwescap.org/stories-of-resiliency/
