### ISSUE TITLE
Video links

### ISSUE THREAD

**Issue by hlthomps** [trinitywebmedia/Norwescap-Tickets#62]
Video to embed on HOMEPAGE (short form), above the text that starts “I'm driven. I take care of myself...: https://www.youtube.com/watch?v=tro3IU8LTj8

Video to embed on www.norwescap.org/give2021 AND on Carrie Ann's Story page (long form): https://www.youtube.com/watch?v=TCXRWL4p5Zg

**Comment by trinitywebmedia** [comment]
Thank you. I will close this out when these two items are completed. -- GT

**Comment by trinitywebmedia** [comment]
The short video is private, can you please change permissions?m -- GT

**Comment by hlthomps** [comment]
It should be public now.

**Comment by trinitywebmedia** [comment]
Teaser is ok. Now, the long one is private - can you please look? Thx.

**Comment by hlthomps** [comment]
Both should now be public.

**Comment by trinitywebmedia** [comment]
DONE
