### ISSUE TITLE
Buttons on mobile view

### ISSUE THREAD

**Issue by hlthomps** [trinitywebmedia/Norwescap-Tickets#64]
The "Get Help Now" button on the homepage is breaking onto a second line on mobile view (screen shot is from iPhone 13, using Chrome browser. Had same result using Safari browser). Can you please check and adjust? Thanks! 
![A6402984-2809-44C9-91C7-0F9C92A96917](https://user-images.githubusercontent.com/83599303/143975657-6677b1f7-50fb-43c6-9fe3-e30891b22ebd.png)

**Comment by trinitywebmedia** [comment]
Ugh. I tested it. Let me look and I will fix -- GT

**Comment by trinitywebmedia** [comment]
My 13 pro shows like this ![image](https://user-images.githubusercontent.com/31321275/143977277-0708eb1e-2e23-4d10-ba44-47bca52168d5.jpeg)

**Comment by trinitywebmedia** [comment]
I'll query widths deeper in the morning

**Comment by hlthomps** [comment]
Thanks. I've got the 13 regular, I think the screen is smaller. My husband has a Samsung Galaxy S20+ and is having the same issue with the button breaking.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by trinitywebmedia** [comment]
Heather - I think I have this fixed. I tested on a browser emulator for iPhone13. Can you please look and make sure we are good? Thanks. -- 
<img width="528" alt="Screen Shot 2021-11-30 at 7 51 04 AM" src="https://user-images.githubusercontent.com/31321275/144051057-96184d3a-cf13-4209-96a7-7c1ff7cecb97.png">
GT

**Comment by hlthomps** [comment]
Looks good on both phones! Thank you!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
