### ISSUE TITLE
Edit to Website

### ISSUE THREAD

**Issue by cfrsnorwescap** [trinitywebmedia/Norwescap-Tickets#66]
https://norwescap.org/education/child-and-family-resource-services/ 

On the above webpage, under the section called "Services:" please make the following edit to the fourth bulleted point. 

Please change "Provide free and confidential referrals for families to early education programs,  child development and other information as well as community resources are also provided to empower families." to "Provide free and confidential referrals for families to early education programs and  community resources for assistance in housing, food, employment, education and other resources to strengthen families."
Please also add a sixth bulleted point with "Support in child screening and development provided."

**Comment by trinitywebmedia** [comment]
Thank you for your detailed instructions. Done -- GT
