### ISSUE TITLE
Add to website

### ISSUE THREAD

**Issue by cfrsnorwescap** [trinitywebmedia/Norwescap-Tickets#68]
https://norwescap.org/education/child-and-family-resource-services/

Please link the attached document to the website at the top of the page above the "November 2021 Reimbursement..." link
and label the link "December 2021 Family Child Care/Approved Home Rate Increase Provider Letter"
[DFDI 21-12-01--Provider Rate. generic.pdf](https://github.com/trinitywebmedia/Norwescap-Tickets/files/7694412/DFDI.21-12-01--Provider.Rate.generic.pdf)

**Comment by trinitywebmedia** [comment]
DONE - GT

**Comment by cfrsnorwescap** [comment]
Hello,
     Can you please label it "December 2021 Family Child Care/Approved Home Rate Increase Provider Letter" instead of "2021 Provider Rates" ?

**Comment by trinitywebmedia** [comment]
Sure -- GT

**Comment by cfrsnorwescap** [comment]
Thank you so much!
