### ISSUE TITLE
Add in Health & Safety Updates Document

### ISSUE THREAD

**Issue by cfrsnorwescap** [trinitywebmedia/Norwescap-Tickets#71]
https://norwescap.org/education/child-and-family-resource-services/

On the above website, please add a link the attached document and label it "Health & Safety Requirement Updates November 2021" and please put it as the last link of the links that are at the top of the page. 

Also, if possible, could you please put a border around or make a box around those links at the top of the page and put the following heading "Current Child Care Services Policies"

[DFDI-21-11-01-Health-and-Safety-Requirement-Updates.pdf](https://github.com/trinitywebmedia/Norwescap-Tickets/files/7721265/DFDI-21-11-01-Health-and-Safety-Requirement-Updates.pdf)

**Comment by trinitywebmedia** [comment]
I did the best we could to accommodate your request within the existing site's constraints. DONE -- GT

**Comment by cfrsnorwescap** [comment]
That is great. Thank you!
