### ISSUE TITLE
Update to link under Additional Resources section

### ISSUE THREAD

**Issue by cfrsnorwescap** [trinitywebmedia/Norwescap-Tickets#72]
https://norwescap.org/education/child-and-family-resource-services/

On the above webpage under the Additional Resources section, please change the link that is next to "Child Care Explorer" from https://data.nj.gov/childcare_explorer  to the new link needed there: https://www.childcarenj.gov/Provider-Search

Thank you!

**Comment by trinitywebmedia** [comment]
DONE -- GT
