### ISSUE TITLE
Add link to DFDI

### ISSUE THREAD

**Issue by cfrsnorwescap** [trinitywebmedia/Norwescap-Tickets#73]
https://norwescap.org/education/child-and-family-resource-services/

On the above website, please add a link to the attached document and label it "DFDI - 22-01-01 Differential Payment Extension" under the top section of Current Child Care Services and Policies
[DFDI 22-01-01--Differential Payment Extension.pdf](https://github.com/trinitywebmedia/Norwescap-Tickets/files/7809536/DFDI.22-01-01--Differential.Payment.Extension.pdf)

Thank you!

**Comment by trinitywebmedia** [comment]
DONE - GT
