### ISSUE TITLE
Updates to Food Bank page

### ISSUE THREAD

**Issue by hlthomps** [trinitywebmedia/Norwescap-Tickets#78]
Please update the text on the Food Bank page, https://norwescap.org/health-wellness/food-bank/, to the text in the attached Word document.

The "click here" in the second paragraph should link to the attached PDF with a list of our area food pantry partners.

Please let me know if you have any questions!
Thanks,
H

[2022 Jan Food Bank page - new language.docx](https://github.com/trinitywebmedia/Norwescap-Tickets/files/7847644/2022.Jan.Food.Bank.page.-.new.language.docx)
[2022 Area Food Pantries.pdf](https://github.com/trinitywebmedia/Norwescap-Tickets/files/7847646/2022.Area.Food.Pantries.pdf)

**Comment by trinitywebmedia** [comment]
Got it. I will have this done by tomorrow. Thanks and Happy New Year.

**Comment by hlthomps** [comment]
Hi - just checking in to make sure everything is ok? Please let me know if there are any questions or issues with these changes. Thanks!

**Comment by trinitywebmedia** [comment]
Completed 1/13 - not marked in GIT. If the changes do not show, please clear cache in Chrome etc. -- Thx. GT

**Comment by hlthomps** [comment]
Thank you, the changes are showing now.

Two quick fixes:
Under "Get Involved", last sentence "Contact us at 908-454-4322 or FoodBank@norwescap.org to learn how you can be part of our work!" - please make sure FoodBank@norwescap.org is a link to email

Under "Thrift Store" first sentence, please add the Google Maps link for the store location: Our thrift store, located at [201 Broad Street, Phillipsburg, NJ](https://goo.gl/maps/JKc6QDNynWgbzJ8r7) and please delete the text "(link to map)"

**Comment by trinitywebmedia** [comment]
Got it. Done. Thx -- GT
