### ISSUE TITLE
Update language on "How We Help" page

### ISSUE THREAD

**Issue by hlthomps** [trinitywebmedia/Norwescap-Tickets#79]
On the page https://norwescap.org/how-we-help/, please replace this text at the top:
Norwescap is a private, non-profit corporation originally established in 1965 under the Economic Opportunity Act to serve the low-income population of throughout Northwest New Jersey.
If you need help please call us at (908) 454-7000

With the text in the attached Word document. The "click here" in the second paragraph should link to (https://portal.empoworbycsst.com/Public/ClientAccessForm.aspx?AccessID=51efa030-cd09-48eb-9e7d-93b00c218be2), the same form we link to from the "Get Assistance" button on our homepage.

Thank you!

[2022 Jan How We Help page update.docx](https://github.com/trinitywebmedia/Norwescap-Tickets/files/7849011/2022.Jan.How.We.Help.page.update.docx)

**Comment by trinitywebmedia** [comment]
Completed 1/13 - Not marked closed. Sorry -- GT
