### ISSUE TITLE
Adjustments/Updates to "Reports and Publications"

### ISSUE THREAD

**Issue by hlthomps** [trinitywebmedia/Norwescap-Tickets#80]
Hi,

Please make the following changes on the page https://norwescap.org/reports-publications/:

Rename "Norwescap Audits" to "Norwescap Audited Financial Statements"
First listing under this category should be renamed "Norwescap Audited Financials FY20" and should link to the attached pdf (currently there is no link)
[Norwescap Audited Financials FY20 (8.31.20).pdf](https://github.com/trinitywebmedia/Norwescap-Tickets/files/7892188/Norwescap.Audited.Financials.FY20.8.31.20.pdf)

Second link should be renamed "Norwescap Audited Financials FY19"
Third link should be renamed "Norwescap Audited Financials FY18"
Fourth link can be removed altogether

Rename "Norwescap 990" to "Norwescap 990 Forms"
Re-order so most recent is on top
Rename "Norwescap 2019 990" to "Norwescap Form 990 FY20 (9/1/2019 - 8/31/2020)" and update link to the attached pdf 
[FY20 Norwescap Form 990 (9.1.19 - 8.31.20).pdf](https://github.com/trinitywebmedia/Norwescap-Tickets/files/7892190/FY20.Norwescap.Form.990.9.1.19.-.8.31.20.pdf)

Rename "Norwescap 2018 990" to "Norwescap Form 990 FY19 (9/1/2018 - 8/31/2019)"
Rename "Norwescap 2017 990" to "Norwescap Form 990 FY18 (9/1/2017 - 8/31/2018)"

Rename "HeadStart Early HeadStart Annual Reports" to "Norwescap Head Start & Early Head Start Program Annual Reports"

thank you!

**Comment by trinitywebmedia** [comment]
Thank you for the detailed instructions. It's appreciated. DONE - GT
