### ISSUE TITLE
Replace link for Get Assistance Form

### ISSUE THREAD

**Issue by hlthomps** [trinitywebmedia/Norwescap-Tickets#83]
Hello,

We need to replace all instances of our current form for people to Get Assistance: https://portal.empoworbycsst.com/Public/ClientAccessForm.aspx?AccessID=51efa030-cd09-48eb-9e7d-93b00c218be2

With this new link: https://portal.empoworbycsst.com/Public/ClientAccessForm.aspx?AccessID=0a6a9913-2187-4e26-bb5b-b31b468cb721

Is this something that can be done universally, or do we need to look into every instance where this is used on the site? Please advise - thank you!
Heather

**Comment by trinitywebmedia** [comment]
We need to know all the pages it's used. I do not know how many instances of the old url are on site.

**Comment by hlthomps** [comment]
Ok - will take some time to pull all of that so I will get back to you when I have it.

**Comment by hlthomps** [comment]
Here are all the pages (I believe) where this link is currently utilized and needs to be replaced:

https://norwescap.org/ - "Get Assistance" red button
https://norwescap.org/ - "Get Assistance" green button
https://norwescap.org/contact-us/ - "Get Help Now" red button
https://norwescap.org/how-we-help/ - "click here" link in 2nd paragraph
"Apply for Assistance" button that appears on the left side of all domain and program pages

Please let me know if any further info is needed. Thanks.

**Comment by trinitywebmedia** [comment]
Thank you for the list. I will have this done by Monday. -- GT

**Comment by trinitywebmedia** [comment]
DONE -- GT
