### ISSUE TITLE
Add Anti-Racism Resolution and language to website

### ISSUE THREAD

**Issue by hlthomps** [trinitywebmedia/Norwescap-Tickets#85]
On the page https://norwescap.org/reports-publications/, please add the attached PDF document as a link called "Anti-Racism Resolution" under the Additional Reports header, above "2020 Covid-19 Report"

On the page https://norwescap.org/our-mission/, please add the following title and two paragraphs of text as a new section underneath "Our Values". In the second paragraph, 3rd sentence, the words "Anti-Racism Resolution" and "here" should both link to the pdf of the full resolution.

Please let me know if you have any questions. Thanks!
Heather

**Our Commitment to Anti-Racism and Equity** (header-style like "Our Values")

Norwescap was founded in 1965 as part of the effort to eliminate poverty during the Civil Rights Movement in the United States, and that remains our central focus today.  While we have made much progress on many fronts since that time, there are still deep, painful disparities that must be addressed.  Central among those remaining issues is that poverty and race remain inextricably linked in the United States of America. This is the painful legacy of slavery, Jim Crow laws, segregation, red-lining, and the institutional racism that still stubbornly insinuates its tentacles into our daily lives.  This truth is at the heart of the work that Norwescap does for the people we serve.  

Racism is wrong and morally repugnant, and we must work together to end it.  We cannot end poverty without addressing racism. To that end, Norwescap has adopted an Anti-Racism Resolution, which you can read in full here. We are committed to the work we must do internally to live up to our resolution, and to creating dialogue and driving progress in the communities we serve, in the State of New Jersey, and in our country.

[Norwescap Anti-Racism Resolution.pdf](https://github.com/trinitywebmedia/Norwescap-Tickets/files/8019113/Norwescap.Anti-Racism.Resolution.pdf)

**Comment by trinitywebmedia** [comment]
DONE -- GT

**Comment by hlthomps** [comment]
Just one quick adjustment, on https://norwescap.org/our-mission/, can you please change the font for "Our Commitment to Anti-Racism and Equity" to match the font used for "Our Values" above?

**Comment by trinitywebmedia** [comment]
I got them to match with some custom CSS. DONE -- GT
