### ISSUE TITLE
New post for "Stories of Resiliency"

### ISSUE THREAD

**Issue by hlthomps** [trinitywebmedia/Norwescap-Tickets#86]
Hello,

Please add the attached story as the first story on https://norwescap.org/stories-of-resiliency/. I am also attaching both a graphic that can be used in the full story, and the photo alone, which will probably be easier for the thumbnail on the main stories page. Please let me know if you have any questions.

Thank you,
Heather
[2022 Feb - Deanna.docx](https://github.com/trinitywebmedia/Norwescap-Tickets/files/8035279/2022.Feb.-.Deanna.docx)
![2022 Feb Deanna Graphic](https://user-images.githubusercontent.com/83599303/153266373-5ab163b2-9805-4805-b83e-54c4115ba8b5.jpg)
![2022 Feb Deanna Homeowner](https://user-images.githubusercontent.com/83599303/153266427-e9f1e811-e6fa-42a6-82a3-8410eb776b6c.png)

**Comment by trinitywebmedia** [comment]
DONE -- GT
