### ISSUE TITLE
New Blog post - Black History Month

### ISSUE THREAD

**Issue by hlthomps** [trinitywebmedia/Norwescap-Tickets#87]
Please post the attached story and graphic as a blog post. The two underlined phrases in the final paragraph ("Anti-Racism Resolution" and "here") should link to https://norwescap.org/wp-content/uploads/2022/02/Norwescap.Anti-Racism.Resolution.pdf. 

Thank you!

[2022 Feb Black History Month.docx](https://github.com/trinitywebmedia/Norwescap-Tickets/files/8044675/2022.Feb.Black.History.Month.docx)
![2022 BHM Graphic](https://user-images.githubusercontent.com/83599303/153505404-7c6f26fe-fa31-4951-abfe-da2d8dbe3e4f.jpg)

**Comment by trinitywebmedia** [comment]
DONE - GT
