### ISSUE TITLE
New Blog post: Phillipsburg 10 year plan

### ISSUE THREAD

**Issue by hlthomps** [trinitywebmedia/Norwescap-Tickets#89]
Good morning,

Please post the text in the attached Word doc as a new blog post. The text "available for review here" in the third paragraph should link to the attached PDF document. An image to use for the post is also attached.

Thank you!
Heather
[2022 Feb Phillipsburg 10 Year Plan update (NRTC).docx](https://github.com/trinitywebmedia/Norwescap-Tickets/files/8097574/2022.Feb.Phillipsburg.10.Year.Plan.update.NRTC.docx)
[Norwescap Phillipsburg South Main Street NRTC 10 Plan Draft.pdf](https://github.com/trinitywebmedia/Norwescap-Tickets/files/8097579/Norwescap.Phillipsburg.South.Main.Street.NRTC.10.Plan.Draft.pdf)
![Downtown South Main Street 2020](https://user-images.githubusercontent.com/83599303/154693330-0271b2d5-aabb-475c-b915-94a0310222a1.jpg)

**Comment by trinitywebmedia** [comment]
DONE - GT

**Comment by hlthomps** [comment]
Hello - 

A couple of adjustments:
- Please make the official title of the blog "Phillipsburg Neighborhood Revitalization: 10 Year Plan" (sorry for the confusion on that)
- Please remove the text "Phillipsburg Neighborhood Revitalization: 10 Year Plan" from the beginning of the actual blog post. It should begin with "Please join Norwescap via Zoom..."
- Please add the text "(scroll down for link and dial-in info)" after "5:30pm to 6:30pm" in the first paragraph, first line

Let me know if any questions. Thanks!

**Comment by trinitywebmedia** [comment]
Got it. Done -- GT

**Comment by hlthomps** [comment]
Hello - I'm not seeing this last round of changes reflected in the post. I tried clearing my cache but no dice. Can you please confirm that the changes were made and published? Thanks!

**Comment by trinitywebmedia** [comment]
![N Post](https://user-images.githubusercontent.com/31321275/155377999-c5eb9c36-c08d-4ac1-8cb6-a97517aa89b8.jpg)
I don't know. It's showing on both of my machines in multiple browsers. Let me clear the site's cache and possibly that will help. -- GT
