### ISSUE TITLE
Add in Link to Brochure

### ISSUE THREAD

**Issue by cfrsnorwescap** [trinitywebmedia/Norwescap-Tickets#92]
https://norwescap.org/education/child-and-family-resource-services/

On the above website, please link the attached brochure & label it "How to Apply for NJ Childcare Subsidy Brochure in English & Spanish"

[How to Apply for NJ Childcare Subsidy Brochure.pdf](https://github.com/trinitywebmedia/Norwescap-Tickets/files/8155667/How.to.Apply.for.NJ.Childcare.Subsidy.Brochure.pdf)

**Comment by trinitywebmedia** [comment]
DONE - GT

**Comment by cfrsnorwescap** [comment]
I apologize. Could you move that link so that it is above the "Applications for Child Care Subsidy" section? I forgot to indicate where to put it.

**Comment by trinitywebmedia** [comment]
No problem -- Done -- GT
