### ISSUE TITLE
Consolidate Application Section

### ISSUE THREAD

**Issue by cfrsnorwescap** [trinitywebmedia/Norwescap-Tickets#93]
https://norwescap.org/education/child-and-family-resource-services/

On the above website, under the "Applications for Child Care Subsidy" section, could you please take out the breakdown of counties below it and put the English/Spanish links to the application next to the heading? Also in the heading please change it to Childcare instead of Child Care. So it would look like: 

Applications for Childcare Subsidy: English/Spanish

**Comment by trinitywebmedia** [comment]
DONE - GT

**Comment by cfrsnorwescap** [comment]
I apologize, but the link goes to the wrong document. I have attached the documents that need to be linked. Also, please put a link to these applications directly next to the heading "Applications for Childcare Subsidy" with the English document labeled as "English" and the Spanish document labeled as "Spanish"

[NJCK Subsidy Application ENGLISH.pdf](https://github.com/trinitywebmedia/Norwescap-Tickets/files/8156648/NJCK.Subsidy.Application.ENGLISH.pdf)

[NJCK Subsidy Application SPANISH.pdf](https://github.com/trinitywebmedia/Norwescap-Tickets/files/8156652/NJCK.Subsidy.Application.SPANISH.pdf)

**Comment by trinitywebmedia** [comment]
DONE
