### ISSUE TITLE
Website Content Edit - Licensed Childcare Information

### ISSUE THREAD

**Issue by cfrsnorwescap** [trinitywebmedia/Norwescap-Tickets#96]
https://norwescap.org/education/child-and-family-resource-services/

On the above website, please replace the content under the heading "Licensed Childcare Information" with the following:

Department of Human Services, Division of Family Development (DHS/DFD) is responsible for promoting safe, affordable and accessible high-quality childcare services in New Jersey. A Licensed Childcare facility is approved by the state Office of Licensing (OOL) for the care, development and supervision of six or more children under 13 years of age who are in care for less than 24 hours a day. Licensed Childcare Centers that are accredited by a national association are programs that have been recognized as high-quality programs. Centers participating in Grow NJ Kids, NJ's Quality Rating and Improvement System, are programs participating in quality activities to continuously improve their program to meet higher quality standards beyond licensing standards.

Childcare inspection reports are now online. The New Jersey Department of Child and Families has created a searchable online database of nearly 4,000 state licensed childcare centers, enabling parents to search for centers and access a center’s state inspection report: https://childcareexplorer.njccis.com/portal/.

Complaints or concerns about a Licensed Childcare Center should be submitted to the Office of Licensing at (877) 667-9845 or submitted online at https://childcareexplorer.njccis.com/portal/. Complaints may be made anonymously.

**Comment by trinitywebmedia** [comment]
DONE -- GT
