### ISSUE TITLE
Edit to Heading

### ISSUE THREAD

**Issue by cfrsnorwescap** [trinitywebmedia/Norwescap-Tickets#97]
https://norwescap.org/health-wellness/sc-diaper-bank/

On the above website,  please change the heading at the top of the page from "SC Diaper Bank" to "Norwescap Diaper Pantry/Caring Closet"

**Comment by trinitywebmedia** [comment]
DONE -- NOTE: I changed the heading, but the url remains the same to preserve all links to this page. - GT

**Comment by cfrsnorwescap** [comment]
Noted. Thank you!
